"""
Credits - Attribution and credits display
==========================================
Scrolling display of all sources, inspirations, and credits
used in the LED Arcade project.

Controls:
  Up/Down  - Slow down / speed up scroll
  Button   - Exit to menu
"""

from . import Visual, Display, Colors, GRID_SIZE
from .credits_data import ATTRIBUTIONS, COUNTS  # generated by tools/build_credits.py

PALETTE = {'C': Colors.CYAN, 'W': Colors.WHITE, 'G': Colors.GRAY, 'M': Colors.MAGENTA}


class Credits(Visual):
    name = "CREDITS"
    description = "Project credits"
    category = "utility"
    GUIDE = {
        'desc': "A scrolling roll of every source, inspiration, and attribution behind the cabinet's games and visuals.",
        'legend': {
            '345/2/4': "The Star Wars automaton's rule: a cell survives with 3, 4 or 5 neighbours, is born with 2, and has 4 states.",
            'SIR MODEL': 'Epidemic model (Susceptible-Infected-Recovered).',
        },
    }

    def __init__(self, display: Display):
        super().__init__(display)

    def reset(self):
        self.time = 0.0
        self.scroll_y = 0.0
        self.base_speed = 12.0    # default pixels per second
        self.scroll_speed = 12.0  # current effective speed
        self.speed_mult = 1.0     # joystick multiplier

        # Build the credits content as (text, color) pairs
        # Each entry is one line; empty string = blank spacer line
        C = Colors.CYAN
        W = Colors.WHITE
        G = Colors.GRAY
        Y = Colors.YELLOW
        M = Colors.MAGENTA

        self.lines = [
            ("LED ARCADE", C),
            ("", G),
            # --- Games ---
            ("- GAMES -", M),
            ("", G),
            ("INSPIRED BY THE", G),
            ("GOLDEN AGE OF", G),
            ("ARCADE GAMES", G),
            ("", G),
            (f"{COUNTS['games']} CLASSIC", W),
            ("GAMES", W),
            ("REIMAGINED", W),
            ("", G),
        ] + [(text, PALETTE[c]) for text, c in ATTRIBUTIONS] + [
            # --- Art ---
            ("- ART -", M),
            ("", G),
            ("SALON GALLERY", C),
            (f"{COUNTS['paintings']} PAINTINGS", W),
            ("", G),
            # --- Demoscene ---
            ("- DEMOSCENE -", M),
            ("", G),
            ("FIRE  PLASMA", W),
            ("ROTOZOOM", W),
            ("SINESCROLL", W),
            ("TWISTER", W),
            ("AMIGA BARS", W),
            ("COPPERBARS", W),
            ("LARSON SCAN", W),
            ("TRANCE", W),
            ("MATRIX", W),
            ("STARFIELD", W),
            ("WONDER CABINET", W),
            ("WIN95 MAZE", W),
            ("CYCLIC", W),
            ("", G),
            # --- Collections ---
            ("- COLLECTIONS -", M),
            ("", G),
            (f"{COUNTS['music']} MUSIC TOOLS", W),
            (f"{COUNTS['cooking']} KITCHEN+TABLE", W),
            (f"{COUNTS['road_rail']} ROAD + RAIL", W),
            ("WORLD CULTURES", W),
            ("", G),
            # --- Data Sources ---
            ("DATA SOURCES", M),
            ("", G),
            ("WIKIMEDIA", W),
            ("COMMONS", W),
            ("MET MUSEUM OA", G),
            ("RCSB PDB", W),
            ("PROTEINS", G),
            ("PEPTIDES", G),
            ("PUBCHEM", W),
            ("MOLECULES", G),
            ("HIPPARCOS ESA", W),
            ("FONTTOOLS", W),
            ("WORLD SCRIPTS", G),
            ("TOMBATOSSALS", W),
            ("CHORDS-DB", G),
            ("", G),
            # --- Resources ---
            ("- RESOURCES -", M),
            ("", G),
            ("FOURMILAB.CH", W),
            ("SIZECODING.ORG", W),
            ("NATUREOFCODE", W),
            ("SHADERTOY.COM", W),
            ("BOOKOFSHADERS", W),
            ("CONWAYLIFE.COM", W),
            ("POUET.NET", W),
            ("NESMAPS.COM", W),
            ("SPRITERS", W),
            ("RESOURCE.COM", G),
            ("FLAGCDN.COM", W),
            ("STELLARIUM.ORG", W),
            ("", G),
            # --- Built With ---
            ("BUILT WITH", G),
            ("PYTHON", C),
            ("RGBMATRIX", C),
            ("RASPBERRY PI", C),
            ("", G),
            # --- Team ---
            ("DESIGNED BY", G),
            ("THISELAZAR", Y),
            ("", G),
            ("PROGRAMMED BY", G),
            ("CLAUDE CODE", Y),
            ("", G),
            ("", G),
        ]

        # Total height needed: each line is 7px (font height + spacing)
        self.line_height = 8
        self.total_height = len(self.lines) * self.line_height

    def handle_input(self, input_state) -> bool:
        if input_state.action_l or input_state.action_r:
            self.wants_exit = True
            return True
        # Joystick controls scroll speed (Smash Bros style)
        if input_state.down:
            self.speed_mult = 4.0   # fast forward
            return True
        elif input_state.up:
            self.speed_mult = -1.5  # rewind
            return True
        else:
            self.speed_mult = 1.0
        return False

    def update(self, dt: float):
        self.time += dt
        self.scroll_speed = self.base_speed * self.speed_mult
        self.scroll_y += self.scroll_speed * dt

        # Clamp: don't scroll above the start
        if self.scroll_y < 0.0:
            self.scroll_y = 0.0

        # Loop when all credits have scrolled past
        if self.scroll_y > self.total_height + GRID_SIZE:
            self.scroll_y = 0.0

    def draw(self):
        self.display.clear(Colors.BLACK)

        for i, (text, color) in enumerate(self.lines):
            if not text:
                continue

            # Calculate screen y position
            y = int(GRID_SIZE - self.scroll_y + i * self.line_height)

            # Only draw if on screen
            if -8 < y < GRID_SIZE:
                self.display.draw_text_small(2, y, text, color)
