"""
DANCE - Dance Forms of the World
=================================
A glowing point traces each dance figure's floor pattern, leaving a
fading ribbon trail that reveals the geometric character of each dance.
Waltz sweeps in curves, tango snaps in straight lines, hula traces
circles.

Data: Codified basic figures from published syllabi (ISTD Bronze,
Vaganova, CLRG, standard syllabus). Generated by tools/build_dance_steps.py.

Controls:
  Up/Down    - Cycle dance families (BALLROOM / FOLK / CLASSICAL / STREET)
  Left/Right - Cycle dances within current family
  Action     - Pause / resume animation
"""

import math
from . import Visual, Display, Colors, GRID_SIZE

# ---------------------------------------------------------------------------
# Families
# ---------------------------------------------------------------------------
FAMILIES = ['BALLROOM', 'FOLK', 'CLASSICAL', 'STREET']

# ---------------------------------------------------------------------------
# Dance data — generated by tools/build_dance_steps.py
# ---------------------------------------------------------------------------
DANCES = [
    {
        'name': 'WALTZ', 'origin': 'Vienna', 'family': 'BALLROOM',
        'tempo': 1.0, 'time_sig': '3/4', 'color': (180, 140, 255),
        'figures': [
            {'name': 'Natural Turn', 'steps': [
                {'foot': 'R', 'x': 16, 'y': 4, 'beat': 1.0, 'action': 'step'},
                {'foot': 'L', 'x': 28, 'y': 16, 'beat': 2.0, 'action': 'step'},
                {'foot': 'R', 'x': 28, 'y': 16, 'beat': 3.0, 'action': 'close'},
                {'foot': 'L', 'x': 28, 'y': 40, 'beat': 1.0, 'action': 'step'},
                {'foot': 'R', 'x': 16, 'y': 28, 'beat': 2.0, 'action': 'step'},
                {'foot': 'L', 'x': 16, 'y': 28, 'beat': 3.0, 'action': 'close'},
            ]},
            {'name': 'Reverse Turn', 'steps': [
                {'foot': 'L', 'x': 28, 'y': 4, 'beat': 1.0, 'action': 'step'},
                {'foot': 'R', 'x': 16, 'y': 16, 'beat': 2.0, 'action': 'step'},
                {'foot': 'L', 'x': 16, 'y': 16, 'beat': 3.0, 'action': 'close'},
                {'foot': 'R', 'x': 16, 'y': 40, 'beat': 1.0, 'action': 'step'},
                {'foot': 'L', 'x': 28, 'y': 28, 'beat': 2.0, 'action': 'step'},
                {'foot': 'R', 'x': 28, 'y': 28, 'beat': 3.0, 'action': 'close'},
            ]},
        ],
    },
    {
        'name': 'TANGO', 'origin': 'Argentina', 'family': 'BALLROOM',
        'tempo': 0.8, 'time_sig': '4/4', 'color': (255, 60, 60),
        'figures': [
            {'name': 'Walk + Link', 'steps': [
                {'foot': 'L', 'x': 14, 'y': 31, 'beat': 1.0, 'action': 'step'},
                {'foot': 'R', 'x': 14, 'y': 31, 'beat': 2.0, 'action': 'step'},
                {'foot': 'L', 'x': 14, 'y': 13, 'beat': 3.0, 'action': 'step'},
                {'foot': 'R', 'x': 30, 'y': 31, 'beat': 4.0, 'action': 'step'},
                {'foot': 'L', 'x': 30, 'y': 31, 'beat': 4.5, 'action': 'close'},
            ]},
            {'name': 'Closed Promenade', 'steps': [
                {'foot': 'L', 'x': 15, 'y': 28, 'beat': 1.0, 'action': 'step'},
                {'foot': 'R', 'x': 29, 'y': 19, 'beat': 2.0, 'action': 'step'},
                {'foot': 'L', 'x': 27, 'y': 16, 'beat': 3.0, 'action': 'step'},
                {'foot': 'R', 'x': 27, 'y': 16, 'beat': 4.0, 'action': 'close'},
            ]},
        ],
    },
    {
        'name': 'FOXTROT', 'origin': 'USA', 'family': 'BALLROOM',
        'tempo': 0.9, 'time_sig': '4/4', 'color': (255, 200, 100),
        'figures': [
            {'name': 'Feather Step', 'steps': [
                {'foot': 'R', 'x': 15, 'y': 31, 'beat': 1.0, 'action': 'step'},
                {'foot': 'L', 'x': 15, 'y': 31, 'beat': 2.0, 'action': 'step'},
                {'foot': 'R', 'x': 29, 'y': 16, 'beat': 3.0, 'action': 'step'},
                {'foot': 'L', 'x': 15, 'y': 13, 'beat': 4.0, 'action': 'step'},
            ]},
            {'name': 'Three Step', 'steps': [
                {'foot': 'R', 'x': 22, 'y': 34, 'beat': 1.0, 'action': 'step'},
                {'foot': 'L', 'x': 22, 'y': 34, 'beat': 2.0, 'action': 'step'},
                {'foot': 'R', 'x': 22, 'y': 10, 'beat': 3.0, 'action': 'step'},
            ]},
        ],
    },
    {
        'name': 'SALSA', 'origin': 'Cuba', 'family': 'STREET',
        'tempo': 1.2, 'time_sig': '4/4', 'color': (255, 100, 50),
        'figures': [
            {'name': 'Basic', 'steps': [
                {'foot': 'L', 'x': 22, 'y': 13, 'beat': 1.0, 'action': 'step'},
                {'foot': 'R', 'x': 22, 'y': 13, 'beat': 2.0, 'action': 'step'},
                {'foot': 'L', 'x': 22, 'y': 13, 'beat': 3.0, 'action': 'close'},
                {'foot': 'R', 'x': 22, 'y': 31, 'beat': 5.0, 'action': 'step'},
                {'foot': 'L', 'x': 22, 'y': 31, 'beat': 6.0, 'action': 'step'},
                {'foot': 'R', 'x': 22, 'y': 31, 'beat': 7.0, 'action': 'close'},
            ]},
            {'name': 'Cross Body Lead', 'steps': [
                {'foot': 'L', 'x': 30, 'y': 13, 'beat': 1.0, 'action': 'step'},
                {'foot': 'R', 'x': 30, 'y': 13, 'beat': 2.0, 'action': 'step'},
                {'foot': 'L', 'x': 14, 'y': 13, 'beat': 3.0, 'action': 'step'},
                {'foot': 'R', 'x': 30, 'y': 31, 'beat': 5.0, 'action': 'step'},
                {'foot': 'L', 'x': 25, 'y': 24, 'beat': 6.0, 'action': 'step'},
                {'foot': 'R', 'x': 25, 'y': 24, 'beat': 7.0, 'action': 'close'},
            ]},
        ],
    },
    {
        'name': 'SWING', 'origin': 'USA', 'family': 'STREET',
        'tempo': 1.2, 'time_sig': '4/4', 'color': (255, 220, 50),
        'figures': [
            {'name': 'East Coast Basic', 'steps': [
                {'foot': 'L', 'x': 17, 'y': 11, 'beat': 1.0, 'action': 'step'},
                {'foot': 'R', 'x': 17, 'y': 11, 'beat': 2.0, 'action': 'close'},
                {'foot': 'R', 'x': 27, 'y': 21, 'beat': 3.0, 'action': 'step'},
                {'foot': 'L', 'x': 27, 'y': 21, 'beat': 4.0, 'action': 'close'},
                {'foot': 'L', 'x': 27, 'y': 33, 'beat': 5.0, 'action': 'step'},
                {'foot': 'R', 'x': 27, 'y': 33, 'beat': 6.0, 'action': 'step'},
            ]},
        ],
    },
    {
        'name': 'SAMBA', 'origin': 'Brazil', 'family': 'STREET',
        'tempo': 1.4, 'time_sig': '2/4', 'color': (0, 200, 100),
        'figures': [
            {'name': 'Basic', 'steps': [
                {'foot': 'L', 'x': 22, 'y': 14, 'beat': 1.0, 'action': 'step'},
                {'foot': 'R', 'x': 22, 'y': 14, 'beat': 1.5, 'action': 'close'},
                {'foot': 'L', 'x': 22, 'y': 14, 'beat': 2.0, 'action': 'step'},
                {'foot': 'R', 'x': 22, 'y': 30, 'beat': 1.0, 'action': 'step'},
                {'foot': 'L', 'x': 22, 'y': 30, 'beat': 1.5, 'action': 'close'},
                {'foot': 'R', 'x': 22, 'y': 30, 'beat': 2.0, 'action': 'step'},
            ]},
            {'name': 'Whisk', 'steps': [
                {'foot': 'L', 'x': 22, 'y': 9, 'beat': 1.0, 'action': 'step'},
                {'foot': 'R', 'x': 22, 'y': 9, 'beat': 1.5, 'action': 'close'},
                {'foot': 'L', 'x': 11, 'y': 20, 'beat': 2.0, 'action': 'step'},
                {'foot': 'R', 'x': 22, 'y': 24, 'beat': 1.0, 'action': 'step'},
                {'foot': 'L', 'x': 22, 'y': 24, 'beat': 1.5, 'action': 'close'},
                {'foot': 'R', 'x': 33, 'y': 35, 'beat': 2.0, 'action': 'step'},
            ]},
        ],
    },
    {
        'name': 'CAPOEIRA', 'origin': 'Brazil', 'family': 'STREET',
        'tempo': 1.0, 'time_sig': '4/4', 'color': (255, 200, 0),
        'figures': [
            {'name': 'Ginga', 'steps': [
                {'foot': 'L', 'x': 16, 'y': 16, 'beat': 1.0, 'action': 'step'},
                {'foot': 'R', 'x': 16, 'y': 16, 'beat': 2.0, 'action': 'step'},
                {'foot': 'L', 'x': 16, 'y': 16, 'beat': 3.0, 'action': 'close'},
                {'foot': 'R', 'x': 28, 'y': 28, 'beat': 4.0, 'action': 'step'},
                {'foot': 'L', 'x': 28, 'y': 28, 'beat': 5.0, 'action': 'step'},
                {'foot': 'R', 'x': 28, 'y': 28, 'beat': 6.0, 'action': 'close'},
            ]},
        ],
    },
    {
        'name': 'BALLET', 'origin': 'France', 'family': 'CLASSICAL',
        'tempo': 0.6, 'time_sig': '3/4', 'color': (200, 180, 255),
        'figures': [
            {'name': 'Pas de Bourree', 'steps': [
                {'foot': 'R', 'x': 18, 'y': 22, 'beat': 1.0, 'action': 'step'},
                {'foot': 'L', 'x': 14, 'y': 22, 'beat': 2.0, 'action': 'step'},
                {'foot': 'R', 'x': 30, 'y': 22, 'beat': 3.0, 'action': 'step'},
            ]},
            {'name': 'Chasse', 'steps': [
                {'foot': 'R', 'x': 14, 'y': 22, 'beat': 1.0, 'action': 'step'},
                {'foot': 'L', 'x': 14, 'y': 22, 'beat': 2.0, 'action': 'close'},
                {'foot': 'R', 'x': 30, 'y': 22, 'beat': 3.0, 'action': 'step'},
                {'foot': 'L', 'x': 30, 'y': 22, 'beat': 4.0, 'action': 'close'},
            ]},
        ],
    },
    {
        'name': 'BHARATA', 'origin': 'India', 'family': 'CLASSICAL',
        'tempo': 0.7, 'time_sig': '4/4', 'color': (255, 180, 50),
        'figures': [
            {'name': 'Tat Adavu', 'steps': [
                {'foot': 'R', 'x': 31, 'y': 22, 'beat': 1.0, 'action': 'stamp'},
                {'foot': 'L', 'x': 31, 'y': 22, 'beat': 2.0, 'action': 'stamp'},
                {'foot': 'L', 'x': 13, 'y': 22, 'beat': 3.0, 'action': 'stamp'},
                {'foot': 'R', 'x': 13, 'y': 22, 'beat': 4.0, 'action': 'stamp'},
            ]},
            {'name': 'Natta Adavu', 'steps': [
                {'foot': 'R', 'x': 37, 'y': 22, 'beat': 1.0, 'action': 'stamp'},
                {'foot': 'L', 'x': 28, 'y': 22, 'beat': 2.0, 'action': 'tap'},
                {'foot': 'L', 'x': 7, 'y': 22, 'beat': 3.0, 'action': 'stamp'},
                {'foot': 'R', 'x': 25, 'y': 22, 'beat': 4.0, 'action': 'tap'},
            ]},
        ],
    },
    {
        'name': 'FLAMENCO', 'origin': 'Spain', 'family': 'FOLK',
        'tempo': 1.1, 'time_sig': '3/4', 'color': (255, 80, 30),
        'figures': [
            {'name': 'Zapateado', 'steps': [
                {'foot': 'R', 'x': 22, 'y': 18, 'beat': 1.0, 'action': 'stamp'},
                {'foot': 'L', 'x': 22, 'y': 18, 'beat': 2.0, 'action': 'stamp'},
                {'foot': 'R', 'x': 22, 'y': 18, 'beat': 3.0, 'action': 'stamp'},
                {'foot': 'L', 'x': 22, 'y': 18, 'beat': 3.5, 'action': 'stamp'},
                {'foot': 'R', 'x': 22, 'y': 26, 'beat': 4.0, 'action': 'stamp'},
                {'foot': 'L', 'x': 22, 'y': 26, 'beat': 4.5, 'action': 'stamp'},
            ]},
        ],
    },
    {
        'name': 'IRISH', 'origin': 'Ireland', 'family': 'FOLK',
        'tempo': 1.3, 'time_sig': '4/4', 'color': (50, 200, 80),
        'figures': [
            {'name': 'Threes', 'steps': [
                {'foot': 'R', 'x': 10, 'y': 22, 'beat': 1.0, 'action': 'step'},
                {'foot': 'L', 'x': 10, 'y': 22, 'beat': 2.0, 'action': 'close'},
                {'foot': 'R', 'x': 22, 'y': 22, 'beat': 3.0, 'action': 'step'},
                {'foot': 'L', 'x': 22, 'y': 22, 'beat': 4.0, 'action': 'step'},
                {'foot': 'R', 'x': 22, 'y': 22, 'beat': 5.0, 'action': 'close'},
                {'foot': 'L', 'x': 34, 'y': 22, 'beat': 6.0, 'action': 'step'},
            ]},
            {'name': 'Sevens', 'steps': [
                {'foot': 'R', 'x': 8, 'y': 22, 'beat': 1.0, 'action': 'step'},
                {'foot': 'L', 'x': 8, 'y': 22, 'beat': 2.0, 'action': 'step'},
                {'foot': 'R', 'x': 18, 'y': 22, 'beat': 3.0, 'action': 'step'},
                {'foot': 'L', 'x': 18, 'y': 22, 'beat': 4.0, 'action': 'step'},
                {'foot': 'R', 'x': 26, 'y': 22, 'beat': 5.0, 'action': 'step'},
                {'foot': 'L', 'x': 26, 'y': 22, 'beat': 6.0, 'action': 'step'},
                {'foot': 'R', 'x': 36, 'y': 22, 'beat': 7.0, 'action': 'step'},
            ]},
        ],
    },
    {
        'name': 'HULA', 'origin': 'Hawaii', 'family': 'FOLK',
        'tempo': 0.6, 'time_sig': '4/4', 'color': (100, 200, 150),
        'figures': [
            {'name': 'Kaholo', 'steps': [
                {'foot': 'R', 'x': 22, 'y': 22, 'beat': 1.0, 'action': 'step'},
                {'foot': 'L', 'x': 22, 'y': 22, 'beat': 2.0, 'action': 'step'},
                {'foot': 'R', 'x': 37, 'y': 22, 'beat': 3.0, 'action': 'step'},
                {'foot': 'L', 'x': 37, 'y': 22, 'beat': 4.0, 'action': 'close'},
                {'foot': 'L', 'x': 22, 'y': 22, 'beat': 5.0, 'action': 'step'},
                {'foot': 'R', 'x': 22, 'y': 22, 'beat': 6.0, 'action': 'step'},
                {'foot': 'L', 'x': 7, 'y': 22, 'beat': 7.0, 'action': 'step'},
                {'foot': 'R', 'x': 7, 'y': 22, 'beat': 8.0, 'action': 'close'},
            ]},
            {'name': 'Ami', 'steps': [
                {'foot': 'R', 'x': 32, 'y': 14, 'beat': 1.0, 'action': 'step'},
                {'foot': 'L', 'x': 29, 'y': 22, 'beat': 2.0, 'action': 'step'},
                {'foot': 'R', 'x': 32, 'y': 26, 'beat': 3.0, 'action': 'step'},
                {'foot': 'L', 'x': 20, 'y': 30, 'beat': 4.0, 'action': 'step'},
                {'foot': 'R', 'x': 20, 'y': 26, 'beat': 5.0, 'action': 'step'},
                {'foot': 'L', 'x': 12, 'y': 22, 'beat': 6.0, 'action': 'step'},
                {'foot': 'R', 'x': 20, 'y': 14, 'beat': 7.0, 'action': 'step'},
                {'foot': 'L', 'x': 20, 'y': 14, 'beat': 8.0, 'action': 'step'},
            ]},
        ],
    },
]

# Build family index
_FAMILY_MAP = {}
for _d in DANCES:
    _FAMILY_MAP.setdefault(_d['family'], []).append(_d)

# Full figure cycles before auto-advance
_AUTO_ADVANCE_CYCLES = 3

# Floor offset: step coords are in ~0-44 range, offset into screen center
_FLOOR_X = 10
_FLOOR_Y = 8

# Animation states
_STATE_TRACING = 0
_STATE_HOLDING = 1
_STATE_FADING = 2

_HOLD_DURATION = 2.0
_FADE_DURATION = 1.0

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _dim(color, factor=0.3):
    return (int(color[0] * factor), int(color[1] * factor),
            int(color[2] * factor))


def _brighten(color, amount=60):
    return (min(255, color[0] + amount), min(255, color[1] + amount),
            min(255, color[2] + amount))


def _alpha_blend(color, alpha):
    return (int(color[0] * alpha), int(color[1] * alpha),
            int(color[2] * alpha))


def _smoothstep(t):
    t = max(0.0, min(1.0, t))
    return t * t * (3.0 - 2.0 * t)


# ---------------------------------------------------------------------------
# Visual
# ---------------------------------------------------------------------------

class Dance(Visual):
    name = "DANCE"
    description = "Dance forms of the world"
    category = "culture"

    def reset(self):
        self._input_cooldown = 0.0
        self.family_idx = 0
        self.dance_idx = 0
        self.paused = False
        self.overlay_timer = 0.0
        self.beat_timer = 0.0
        self._select_dance()

    def _select_dance(self):
        family = FAMILIES[self.family_idx]
        dances = _FAMILY_MAP.get(family, [])
        if not dances:
            self.dance_idx = 0
            return
        self.dance_idx = self.dance_idx % len(dances)
        self.current = dances[self.dance_idx]
        self.overlay_timer = 2.5
        self._fig_idx = 0
        self._cycle_count = 0
        self._start_figure()

    def _start_figure(self):
        """Begin tracing the current figure."""
        fig = self._current_figure()
        steps = fig['steps']

        # Build waypoints in screen coords
        self._waypoints = []
        self._step_feet = []
        for s in steps:
            self._waypoints.append((s['x'] + _FLOOR_X, s['y'] + _FLOOR_Y))
            self._step_feet.append(s['foot'])

        self._state = _STATE_TRACING
        self._seg_idx = 0        # which segment we're tracing (between wp i and i+1)
        self._seg_t = 0.0        # 0..1 within current segment
        self._trail = []         # list of (x, y) float tuples — the ribbon
        self._markers = []       # (x, y, foot) at waypoints the head has passed
        self._hold_timer = 0.0
        self._fade_timer = 0.0
        self._glow_phase = 0.0

        # Place first marker
        if self._waypoints:
            wp = self._waypoints[0]
            self._markers.append((wp[0], wp[1], self._step_feet[0]))

    def _current_figure(self):
        figs = self.current['figures']
        return figs[self._fig_idx % len(figs)]

    def _head_pos(self):
        """Current head position via smoothstep interpolation between waypoints."""
        wp = self._waypoints
        if not wp:
            return (32.0, 32.0)
        i = min(self._seg_idx, len(wp) - 2)
        if i < 0:
            return (float(wp[0][0]), float(wp[0][1]))
        t = _smoothstep(self._seg_t)
        x = wp[i][0] + (wp[i + 1][0] - wp[i][0]) * t
        y = wp[i][1] + (wp[i + 1][1] - wp[i][1]) * t
        return (x, y)

    def _advance_figure(self):
        figs = self.current['figures']
        self._fig_idx += 1
        if self._fig_idx >= len(figs):
            self._fig_idx = 0
            self._cycle_count += 1
            if self._cycle_count >= _AUTO_ADVANCE_CYCLES:
                self._advance_dance()
                return
        self._start_figure()

    def _advance_dance(self):
        family = FAMILIES[self.family_idx]
        n = len(_FAMILY_MAP.get(family, []))
        if n > 1:
            self.dance_idx = (self.dance_idx + 1) % n
        else:
            self.family_idx = (self.family_idx + 1) % len(FAMILIES)
            self.dance_idx = 0
        self._select_dance()

    def handle_input(self, input_state):
        if self._input_cooldown > 0:
            return False

        consumed = False

        if input_state.up_pressed:
            self.family_idx = (self.family_idx - 1) % len(FAMILIES)
            self.dance_idx = 0
            self._select_dance()
            consumed = True
        elif input_state.down_pressed:
            self.family_idx = (self.family_idx + 1) % len(FAMILIES)
            self.dance_idx = 0
            self._select_dance()
            consumed = True

        if not consumed:
            family = FAMILIES[self.family_idx]
            n = len(_FAMILY_MAP.get(family, []))
            if input_state.left_pressed and n > 0:
                self.dance_idx = (self.dance_idx - 1) % n
                self._select_dance()
                consumed = True
            elif input_state.right_pressed and n > 0:
                self.dance_idx = (self.dance_idx + 1) % n
                self._select_dance()
                consumed = True

        if not consumed and (input_state.action_l or input_state.action_r):
            self.paused = not self.paused
            consumed = True

        if consumed:
            self._input_cooldown = 0.15
        return consumed

    # -------------------------------------------------------------------
    # Update
    # -------------------------------------------------------------------

    def update(self, dt):
        super().update(dt)
        if self._input_cooldown > 0:
            self._input_cooldown = max(0.0, self._input_cooldown - dt)
        if self.overlay_timer > 0:
            self.overlay_timer -= dt

        # Beat timer for indicator
        self.beat_timer += dt * self.current['tempo']
        if self.beat_timer >= 1.0:
            self.beat_timer -= 1.0

        self._glow_phase += dt * 5.0

        if self.paused:
            return

        n_segs = len(self._waypoints) - 1

        if self._state == _STATE_TRACING:
            if n_segs <= 0:
                self._state = _STATE_HOLDING
                self._hold_timer = 0.0
                return

            tempo = self.current['tempo']
            beat_dur = 1.0 / tempo
            self._seg_t += dt / beat_dur

            # Sample head position into trail
            hx, hy = self._head_pos()
            self._trail.append((hx, hy))

            # Advance segments
            while self._seg_t >= 1.0 and self._seg_idx < n_segs:
                self._seg_t -= 1.0
                self._seg_idx += 1

                if self._seg_idx < n_segs:
                    wp = self._waypoints[self._seg_idx]
                    self._markers.append((wp[0], wp[1],
                                          self._step_feet[self._seg_idx]))
                else:
                    # Arrived at final waypoint
                    wp = self._waypoints[-1]
                    self._markers.append((wp[0], wp[1],
                                          self._step_feet[-1]))
                    self._state = _STATE_HOLDING
                    self._hold_timer = 0.0
                    # Final trail sample at exact endpoint
                    self._trail.append((float(wp[0]), float(wp[1])))

        elif self._state == _STATE_HOLDING:
            self._hold_timer += dt
            if self._hold_timer >= _HOLD_DURATION:
                self._state = _STATE_FADING
                self._fade_timer = 0.0

        elif self._state == _STATE_FADING:
            self._fade_timer += dt
            if self._fade_timer >= _FADE_DURATION:
                self._advance_figure()

    # -------------------------------------------------------------------
    # Drawing helpers
    # -------------------------------------------------------------------

    def _draw_floor_trace(self, dance):
        d = self.display
        color = dance['color']
        bright = _brighten(color, 80)

        # Master fade for FADING state
        fade = 1.0
        if self._state == _STATE_FADING:
            fade = max(0.0, 1.0 - self._fade_timer / _FADE_DURATION)

        # Dim center cross
        cx, cy = 32, 31
        cross_c = _alpha_blend((35, 35, 35), fade)
        for i in range(-1, 2):
            d.set_pixel(cx + i, cy, cross_c)
            d.set_pixel(cx, cy + i, cross_c)

        # --- Trail ribbon ---
        trail = self._trail
        n = len(trail)
        if n >= 2:
            # Subsample when trail is very long to keep draw calls bounded
            step = max(1, n // 300)
            for i in range(step, n, step):
                # Age: 0.0 = oldest, 1.0 = newest
                age = i / (n - 1)

                if self._state == _STATE_TRACING:
                    alpha = (0.12 + 0.88 * age) * fade
                else:
                    alpha = 0.7 * fade

                tc = _alpha_blend(color, alpha)
                j = max(0, i - step)
                x0, y0 = int(trail[j][0]), int(trail[j][1])
                x1, y1 = int(trail[i][0]), int(trail[i][1])
                if x0 == x1 and y0 == y1:
                    d.set_pixel(x0, y0, tc)
                else:
                    d.draw_line(x0, y0, x1, y1, tc)

        # --- Step markers at waypoints ---
        for i, (mx, my, foot) in enumerate(self._markers):
            mc = bright if foot == 'R' else color
            mc = _alpha_blend(mc, 0.9 * fade)
            ix, iy = int(mx), int(my)
            d.set_pixel(ix, iy, mc)
            # Small number near marker
            if len(self._markers) <= 9 or i >= len(self._markers) - 7:
                nc = _alpha_blend((90, 90, 90), fade * 0.6)
                d.draw_text_small(ix + 2, iy - 2, str(i + 1), nc)

        # --- Head glow (only while tracing) ---
        if self._state == _STATE_TRACING and n > 0:
            hx, hy = trail[-1]
            ix, iy = int(hx), int(hy)
            pulse = 0.7 + 0.3 * math.sin(self._glow_phase)

            # Bright white center
            wc = _alpha_blend((255, 255, 255), pulse)
            d.set_pixel(ix, iy, wc)

            # Colored glow ring
            gc = _alpha_blend(bright, pulse * 0.7)
            for dx, dy in ((-1, 0), (1, 0), (0, -1), (0, 1)):
                px, py = ix + dx, iy + dy
                if 0 <= px < 64 and 0 <= py < 64:
                    d.set_pixel(px, py, gc)

            # Faint outer glow
            oc = _alpha_blend(color, pulse * 0.25)
            for dx, dy in ((-1, -1), (1, -1), (-1, 1), (1, 1)):
                px, py = ix + dx, iy + dy
                if 0 <= px < 64 and 0 <= py < 64:
                    d.set_pixel(px, py, oc)

    def _draw_beat_indicator(self, dance):
        d = self.display
        color = dance['color']
        time_sig = dance['time_sig']
        beats = int(time_sig.split('/')[0]) if '/' in time_sig else 4
        beats = min(beats, 4)

        total_w = beats * 4 - 2
        start_x = 32 - total_w // 2
        current_beat = int(self.beat_timer * beats) % beats

        for b in range(beats):
            bx = start_x + b * 4
            if b == current_beat:
                phase = (self.beat_timer * beats) % 1.0
                ba = max(0.2, 1.0 - phase * 1.5)
                bc = _alpha_blend(color, ba)
            else:
                bc = _dim(color, 0.15)
            d.set_pixel(bx, 57, bc)
            d.set_pixel(bx + 1, 57, bc)

    def _draw_family_dots(self):
        d = self.display
        family = FAMILIES[self.family_idx]
        dances = _FAMILY_MAP.get(family, [])
        n = len(dances)
        if n <= 1:
            return
        total_w = n * 3 - 1
        start_x = 32 - total_w // 2
        for i in range(n):
            dx = start_x + i * 3
            c = (180, 180, 180) if i == self.dance_idx else (50, 50, 50)
            d.set_pixel(dx, 62, c)

    def _draw_overlay(self, dance):
        if self.overlay_timer <= 0:
            return
        d = self.display
        alpha = min(1.0, self.overlay_timer / 0.5)
        color = dance['color']

        d.draw_text_small(2, 1, dance['name'], _alpha_blend(color, alpha))
        d.draw_text_small(48, 1, dance['time_sig'],
                          _alpha_blend((200, 200, 200), alpha * 0.7))
        d.draw_text_small(2, 55, dance['origin'],
                          _alpha_blend((160, 160, 160), alpha * 0.6))

    # -------------------------------------------------------------------
    # Main draw
    # -------------------------------------------------------------------

    def draw(self):
        d = self.display
        d.clear()
        dance = self.current
        color = dance['color']
        fig = self._current_figure()

        # Floor trace
        self._draw_floor_trace(dance)

        # Beat indicator
        self._draw_beat_indicator(dance)

        # Family dots
        self._draw_family_dots()

        # Persistent dim header
        if self.overlay_timer <= 0:
            d.draw_text_small(2, 1, dance['name'], _dim(color, 0.5))
            d.draw_text_small(48, 1, dance['time_sig'], (60, 60, 60))
            # Figure name bottom
            fig_alpha = 1.0
            if self._state == _STATE_FADING:
                fig_alpha = max(0.0, 1.0 - self._fade_timer / _FADE_DURATION)
            d.draw_text_small(2, 55, fig['name'],
                              _alpha_blend(_dim(color, 0.4), fig_alpha))

        # Overlay (fades out)
        self._draw_overlay(dance)

        # Pause indicator
        if self.paused:
            d.draw_text_small(26, 30, "||", (200, 200, 200))
