"""
FLAGS OF THE WORLD - National Flag Display
============================================
120+ country flags loaded from PNG files in assets/flags/.
Flag images sourced from flagcdn.com, pre-rendered at 60x40 via tools/build_flags.py.
"""

import os
try:
    from PIL import Image
    HAS_PIL = True
except ImportError:
    HAS_PIL = False
from . import Visual, Colors

# Pre-loaded pixel data for emulator mode (injected before this module loads)
_PRELOADED_FLAGS = globals().get('_FLAGS_PIXELS', {})

# Flag dimensions and position
FLAG_W, FLAG_H = 60, 40
FX = (64 - FLAG_W) // 2
FY = 6

ASSETS_DIR = os.path.join(os.path.dirname(__file__), '..', 'assets', 'flags')

# (display_name, continent, iso_code) — generated by tools/build_flags.py
FLAG_MANIFEST = [
    # ===== AFRICA =====
    ('ALGERIA', 'AFRICA', 'dz'),
    ('CAMEROON', 'AFRICA', 'cm'),
    ('CHAD', 'AFRICA', 'td'),
    ('EGYPT', 'AFRICA', 'eg'),
    ('ETHIOPIA', 'AFRICA', 'et'),
    ('GHANA', 'AFRICA', 'gh'),
    ('IVORY COAST', 'AFRICA', 'ci'),
    ('KENYA', 'AFRICA', 'ke'),
    ('LIBYA', 'AFRICA', 'ly'),
    ('MADAGASCAR', 'AFRICA', 'mg'),
    ('MALI', 'AFRICA', 'ml'),
    ('MOROCCO', 'AFRICA', 'ma'),
    ('MOZAMBIQUE', 'AFRICA', 'mz'),
    ('NIGER', 'AFRICA', 'ne'),
    ('NIGERIA', 'AFRICA', 'ng'),
    ('SENEGAL', 'AFRICA', 'sn'),
    ('SOUTH AFRICA', 'AFRICA', 'za'),
    ('TANZANIA', 'AFRICA', 'tz'),
    ('TUNISIA', 'AFRICA', 'tn'),
    ('UGANDA', 'AFRICA', 'ug'),
    # ===== AMERICAS =====
    ('ARGENTINA', 'AMERICAS', 'ar'),
    ('BAHAMAS', 'AMERICAS', 'bs'),
    ('BOLIVIA', 'AMERICAS', 'bo'),
    ('BRAZIL', 'AMERICAS', 'br'),
    ('CANADA', 'AMERICAS', 'ca'),
    ('CHILE', 'AMERICAS', 'cl'),
    ('COLOMBIA', 'AMERICAS', 'co'),
    ('COSTA RICA', 'AMERICAS', 'cr'),
    ('CUBA', 'AMERICAS', 'cu'),
    ('DOM. REPUBLIC', 'AMERICAS', 'do'),
    ('ECUADOR', 'AMERICAS', 'ec'),
    ('EL SALVADOR', 'AMERICAS', 'sv'),
    ('GUATEMALA', 'AMERICAS', 'gt'),
    ('HAITI', 'AMERICAS', 'ht'),
    ('HONDURAS', 'AMERICAS', 'hn'),
    ('JAMAICA', 'AMERICAS', 'jm'),
    ('MEXICO', 'AMERICAS', 'mx'),
    ('NICARAGUA', 'AMERICAS', 'ni'),
    ('PANAMA', 'AMERICAS', 'pa'),
    ('PARAGUAY', 'AMERICAS', 'py'),
    ('PERU', 'AMERICAS', 'pe'),
    ('TRINIDAD', 'AMERICAS', 'tt'),
    ('URUGUAY', 'AMERICAS', 'uy'),
    ('USA', 'AMERICAS', 'us'),
    ('VENEZUELA', 'AMERICAS', 've'),
    # ===== ASIA =====
    ('BANGLADESH', 'ASIA', 'bd'),
    ('CAMBODIA', 'ASIA', 'kh'),
    ('CHINA', 'ASIA', 'cn'),
    ('INDIA', 'ASIA', 'in'),
    ('INDONESIA', 'ASIA', 'id'),
    ('IRAN', 'ASIA', 'ir'),
    ('IRAQ', 'ASIA', 'iq'),
    ('ISRAEL', 'ASIA', 'il'),
    ('JAPAN', 'ASIA', 'jp'),
    ('JORDAN', 'ASIA', 'jo'),
    ('KUWAIT', 'ASIA', 'kw'),
    ('LAOS', 'ASIA', 'la'),
    ('LEBANON', 'ASIA', 'lb'),
    ('MALAYSIA', 'ASIA', 'my'),
    ('MONGOLIA', 'ASIA', 'mn'),
    ('MYANMAR', 'ASIA', 'mm'),
    ('NEPAL', 'ASIA', 'np'),
    ('NORTH KOREA', 'ASIA', 'kp'),
    ('PAKISTAN', 'ASIA', 'pk'),
    ('PALESTINE', 'ASIA', 'ps'),
    ('PHILIPPINES', 'ASIA', 'ph'),
    ('QATAR', 'ASIA', 'qa'),
    ('SAUDI ARABIA', 'ASIA', 'sa'),
    ('SINGAPORE', 'ASIA', 'sg'),
    ('SOUTH KOREA', 'ASIA', 'kr'),
    ('SRI LANKA', 'ASIA', 'lk'),
    ('THAILAND', 'ASIA', 'th'),
    ('TURKEY', 'ASIA', 'tr'),
    ('UAE', 'ASIA', 'ae'),
    ('UZBEKISTAN', 'ASIA', 'uz'),
    ('VIETNAM', 'ASIA', 'vn'),
    # ===== EUROPE =====
    ('ALBANIA', 'EUROPE', 'al'),
    ('AUSTRIA', 'EUROPE', 'at'),
    ('BELGIUM', 'EUROPE', 'be'),
    ('BULGARIA', 'EUROPE', 'bg'),
    ('CROATIA', 'EUROPE', 'hr'),
    ('CZECH REPUBLIC', 'EUROPE', 'cz'),
    ('DENMARK', 'EUROPE', 'dk'),
    ('ESTONIA', 'EUROPE', 'ee'),
    ('FINLAND', 'EUROPE', 'fi'),
    ('FRANCE', 'EUROPE', 'fr'),
    ('GERMANY', 'EUROPE', 'de'),
    ('GREECE', 'EUROPE', 'gr'),
    ('HUNGARY', 'EUROPE', 'hu'),
    ('ICELAND', 'EUROPE', 'is'),
    ('IRELAND', 'EUROPE', 'ie'),
    ('ITALY', 'EUROPE', 'it'),
    ('LATVIA', 'EUROPE', 'lv'),
    ('LITHUANIA', 'EUROPE', 'lt'),
    ('LUXEMBOURG', 'EUROPE', 'lu'),
    ('MALTA', 'EUROPE', 'mt'),
    ('MONACO', 'EUROPE', 'mc'),
    ('NETHERLANDS', 'EUROPE', 'nl'),
    ('NORWAY', 'EUROPE', 'no'),
    ('POLAND', 'EUROPE', 'pl'),
    ('PORTUGAL', 'EUROPE', 'pt'),
    ('ROMANIA', 'EUROPE', 'ro'),
    ('RUSSIA', 'EUROPE', 'ru'),
    ('SERBIA', 'EUROPE', 'rs'),
    ('SLOVAKIA', 'EUROPE', 'sk'),
    ('SLOVENIA', 'EUROPE', 'si'),
    ('SPAIN', 'EUROPE', 'es'),
    ('SWEDEN', 'EUROPE', 'se'),
    ('SWITZERLAND', 'EUROPE', 'ch'),
    ('UK', 'EUROPE', 'gb'),
    ('UKRAINE', 'EUROPE', 'ua'),
    # ===== OCEANIA =====
    ('AUSTRALIA', 'OCEANIA', 'au'),
    ('FIJI', 'OCEANIA', 'fj'),
    ('MARSHALL IS.', 'OCEANIA', 'mh'),
    ('MICRONESIA', 'OCEANIA', 'fm'),
    ('NAURU', 'OCEANIA', 'nr'),
    ('NEW ZEALAND', 'OCEANIA', 'nz'),
    ('PALAU', 'OCEANIA', 'pw'),
    ('PAPUA N.G.', 'OCEANIA', 'pg'),
    ('SAMOA', 'OCEANIA', 'ws'),
    ('SOLOMON IS.', 'OCEANIA', 'sb'),
    ('TONGA', 'OCEANIA', 'to'),
    ('VANUATU', 'OCEANIA', 'vu'),
]

# ---------------------------------------------------------------------------
# Groups
# ---------------------------------------------------------------------------
GROUPS = [
    ('ALL',      'ALL COUNTRIES'),
    ('AFRICA',   'AFRICA'),
    ('AMERICAS', 'AMERICAS'),
    ('ASIA',     'ASIA'),
    ('EUROPE',   'EUROPE'),
    ('OCEANIA',  'OCEANIA'),
]


def _build_group_indices():
    all_sorted = sorted(range(len(FLAG_MANIFEST)), key=lambda i: FLAG_MANIFEST[i][0])
    indices = {'ALL': all_sorted}
    for key in ['AFRICA', 'AMERICAS', 'ASIA', 'EUROPE', 'OCEANIA']:
        indices[key] = [i for i, f in enumerate(FLAG_MANIFEST) if f[1] == key]
    return indices


def _load_flag_png(iso_code):
    """Load a flag PNG and return pixel rows as list of lists of RGB tuples."""
    # Emulator mode: decode from pre-loaded base64 atlas
    b64 = _PRELOADED_FLAGS.get(iso_code)
    if b64:
        import base64
        raw = base64.b64decode(b64)
        pixels = []
        for y in range(FLAG_H):
            row = []
            for x in range(FLAG_W):
                i = (y * FLAG_W + x) * 3
                row.append((raw[i], raw[i + 1], raw[i + 2]))
            pixels.append(row)
        return pixels
    # Hardware mode: load PNG via PIL
    path = os.path.join(ASSETS_DIR, f"{iso_code}.png")
    img = Image.open(path).convert('RGB')
    raw = img.tobytes()
    w = img.width
    pixels = []
    for y in range(img.height):
        row = []
        offset = y * w * 3
        for x in range(w):
            i = offset + x * 3
            row.append((raw[i], raw[i + 1], raw[i + 2]))
        pixels.append(row)
    return pixels


class Flags(Visual):
    name = "FLAGS"
    description = "Flags of the world"
    category = "road_rail"

    def reset(self):
        self.time = 0.0
        self.group_indices = _build_group_indices()
        self.group_idx = 0
        self.flag_pos = 0
        self.auto_cycle = True
        self.cycle_timer = 0.0
        self.cycle_duration = 5.0
        self.overlay_timer = 0.0
        self.scroll_offset = 0.0
        self._pixel_cache = {}

    def _current_list(self):
        key = GROUPS[self.group_idx][0]
        return self.group_indices.get(key, [])

    def _current_flag(self):
        lst = self._current_list()
        if not lst:
            return FLAG_MANIFEST[0]
        return FLAG_MANIFEST[lst[self.flag_pos % len(lst)]]

    def _get_pixels(self, iso_code):
        """Load flag pixels, caching for reuse."""
        if iso_code not in self._pixel_cache:
            self._pixel_cache[iso_code] = _load_flag_png(iso_code)
        return self._pixel_cache[iso_code]

    def handle_input(self, input_state):
        consumed = False
        if input_state.up_pressed:
            self.group_idx = (self.group_idx - 1) % len(GROUPS)
            self.flag_pos = 0
            self.cycle_timer = 0.0
            self.overlay_timer = 2.5
            consumed = True
        if input_state.down_pressed:
            self.group_idx = (self.group_idx + 1) % len(GROUPS)
            self.flag_pos = 0
            self.cycle_timer = 0.0
            self.overlay_timer = 2.5
            consumed = True
        if input_state.left_pressed:
            lst = self._current_list()
            if lst:
                self.flag_pos = (self.flag_pos - 1) % len(lst)
            self.cycle_timer = 0.0
            self.scroll_offset = 0.0
            consumed = True
        if input_state.right_pressed:
            lst = self._current_list()
            if lst:
                self.flag_pos = (self.flag_pos + 1) % len(lst)
            self.cycle_timer = 0.0
            self.scroll_offset = 0.0
            consumed = True
        if input_state.action_l or input_state.action_r:
            self.auto_cycle = not self.auto_cycle
            consumed = True
        return consumed

    def update(self, dt):
        self.time += dt
        self.scroll_offset += dt * 20
        if self.overlay_timer > 0:
            self.overlay_timer = max(0.0, self.overlay_timer - dt)

        if self.auto_cycle:
            self.cycle_timer += dt
            if self.cycle_timer >= self.cycle_duration:
                self.cycle_timer = 0.0
                lst = self._current_list()
                if lst:
                    self.flag_pos = (self.flag_pos + 1) % len(lst)
                self.scroll_offset = 0.0

    def _draw_usa_overdraw(self, d):
        """Overdraw crisp stripes, canton, and stars on the USA flag."""
        RED = (178, 34, 52)
        WHITE = (255, 255, 255)
        NAVY = (10, 49, 97)
        # 13 stripes across 40px height
        stripe_tops = [round(i * FLAG_H / 13) for i in range(14)]
        for s in range(13):
            color = RED if s % 2 == 0 else WHITE
            for y in range(stripe_tops[s], stripe_tops[s + 1]):
                for x in range(FLAG_W):
                    d.set_pixel(FX + x, FY + y, color)
        # Canton over top 7 stripes, 2/5 width
        cw = 24
        ch = stripe_tops[7]
        for y in range(ch):
            for x in range(cw):
                d.set_pixel(FX + x, FY + y, NAVY)
        # 50 stars: 5 rows of 6 + 4 rows of 5 (staggered)
        for row in range(9):
            sy = FY + 2 + row * 2
            if sy >= FY + ch:
                break
            if row % 2 == 0:  # 6-star rows
                for col in range(6):
                    d.set_pixel(FX + 1 + col * 4, sy, WHITE)
            else:  # 5-star rows (offset)
                for col in range(5):
                    d.set_pixel(FX + 3 + col * 4, sy, WHITE)

    def draw(self):
        d = self.display
        d.clear()

        flag = self._current_flag()
        name, continent, iso_code = flag
        pixels = self._get_pixels(iso_code)

        # Blit flag pixel data
        for y, row in enumerate(pixels):
            for x, color in enumerate(row):
                d.set_pixel(FX + x, FY + y, color)

        # USA: overdraw canton with crisp stars
        if iso_code == 'us':
            self._draw_usa_overdraw(d)

        # Flag border
        d.draw_rect(FX - 1, FY - 1, FLAG_W + 2, FLAG_H + 2,
                     (40, 40, 40), filled=False)

        # Country name at bottom
        label = name
        label_y = FY + FLAG_H + 4
        max_chars = 14
        if len(label) > max_chars:
            padded = label + "    " + label
            total_w = len(label + "    ") * 4
            offset = int(self.scroll_offset) % total_w
            d.draw_text_small(2 - offset, label_y, padded, Colors.WHITE)
        else:
            d.draw_text_small(2, label_y, label, Colors.WHITE)

        # Group overlay
        if self.overlay_timer > 0:
            _, gname = GROUPS[self.group_idx]
            alpha = min(1.0, self.overlay_timer / 0.5)
            c = (int(200 * alpha), int(200 * alpha), int(200 * alpha))
            d.draw_text_small(2, 2, gname, c)
