"""
Painting Collection
===================
Auto-generated painting visuals from the LED Arcade painting pipeline.
Each painting appears as its own entry in the ART category.

Controls:
  Left/Right - Cycle between paintings
  Action     - Show info overlay
"""

import os
import unicodedata
from . import Visual, Display, Colors, GRID_SIZE


def _strip_accents(s):
    """Replace accented characters with ASCII equivalents for LED font."""
    nfkd = unicodedata.normalize('NFKD', s)
    return ''.join(c for c in nfkd if not unicodedata.combining(c))

try:
    from PIL import Image
    HAS_PIL = True
except ImportError:
    HAS_PIL = False

# Pre-loaded pixel data for emulator mode (injected before this module loads)
_PRELOADED = globals().get('_PAINTING_PIXELS', {})

# Metadata: pid -> (title, artist, year)
# Generated by: python tools/build_paintings.py --meta
PAINTING_META = {
    "mona_lisa": ("Mona Lisa", "Leonardo da Vinci", 1503),
    "last_supper": ("The Last Supper", "Leonardo da Vinci", 1498),
    "lady_ermine": ("Lady with an Ermine", "Leonardo da Vinci", 1490),
    "creation_of_adam": ("The Creation of Adam", "Michelangelo", 1512),
    "sistine_madonna": ("Sistine Madonna", "Raphael", 1512),
    "school_of_athens": ("The School of Athens", "Raphael", 1511),
    "botticelli_annunciation": ("Cestello Annunciation", "Sandro Botticelli", 1489),
    "fra_angelico_annunciation": ("The Annunciation", "Fra Angelico", 1440),
    "garden_earthly_delights": ("The Garden of Earthly Delights", "Hieronymus Bosch", 1500),
    "last_judgment_bosch": ("The Last Judgment", "Hieronymus Bosch", 1482),
    "tower_of_babel": ("The Tower of Babel", "Pieter Bruegel", 1563),
    "hunters_snow": ("Hunters in the Snow", "Pieter Bruegel", 1565),
    "arcimboldo_summer": ("Summer", "Giuseppe Arcimboldo", 1563),
    "durer_self_portrait": ("Self-Portrait at Twenty-Eight", "Albrecht Dürer", 1500),
    "arnolfini_portrait": ("The Arnolfini Portrait", "Jan van Eyck", 1434),
    "titian_assumption": ("Assumption of the Virgin", "Titian", 1518),
    "caravaggio_bacchus": ("Bacchus", "Caravaggio", 1598),
    "calling_st_matthew": ("The Calling of Saint Matthew", "Caravaggio", 1600),
    "supper_emmaus": ("The Supper at Emmaus", "Caravaggio", 1601),
    "caravaggio_medusa": ("Medusa", "Caravaggio", 1597),
    "gentileschi_self_portrait": ("Self-Portrait as Allegory of Painting", "Artemisia Gentileschi", 1639),
    "girl_pearl_earring": ("Girl with a Pearl Earring", "Johannes Vermeer", 1665),
    "the_milkmaid": ("The Milkmaid", "Johannes Vermeer", 1658),
    "art_of_painting": ("The Art of Painting", "Johannes Vermeer", 1666),
    "girl_reading_letter": ("Girl Reading a Letter at an Open Window", "Johannes Vermeer", 1657),
    "vermeer_astronomer": ("The Astronomer", "Johannes Vermeer", 1668),
    "view_of_delft": ("View of Delft", "Johannes Vermeer", 1661),
    "night_watch": ("The Night Watch", "Rembrandt", 1642),
    "rembrandt_self_portrait": ("Self-Portrait", "Rembrandt", 1660),
    "las_meninas": ("Las Meninas", "Diego Velázquez", 1656),
    "the_swing": ("The Swing", "Jean-Honoré Fragonard", 1767),
    "goya_parasol": ("The Parasol", "Francisco Goya", 1777),
    "death_of_marat": ("The Death of Marat", "Jacques-Louis David", 1793),
    "napoleon_alps": ("Napoleon Crossing the Alps", "Jacques-Louis David", 1801),
    "wanderer_fog": ("Wanderer Above the Sea of Fog", "Caspar David Friedrich", 1818),
    "death_sardanapalus": ("The Death of Sardanapalus", "Eugène Delacroix", 1827),
    "horse_fair": ("The Horse Fair", "Rosa Bonheur", 1853),
    "raft_of_medusa": ("The Raft of the Medusa", "Théodore Géricault", 1819),
    "epsom_derby": ("The Derby at Epsom", "Théodore Géricault", 1821),
    "fighting_temeraire": ("The Fighting Temeraire", "J.M.W. Turner", 1839),
    "rain_steam_speed": ("Rain, Steam and Speed", "J.M.W. Turner", 1844),
    "hay_wain": ("The Hay Wain", "John Constable", 1821),
    "the_oxbow": ("The Oxbow", "Thomas Cole", 1836),
    "niagara": ("Niagara", "Frederic Edwin Church", 1857),
    "ninth_wave": ("The Ninth Wave", "Ivan Aivazovsky", 1850),
    "great_wave": ("The Great Wave off Kanagawa", "Katsushika Hokusai", 1831),
    "red_fuji": ("Fine Wind, Clear Morning", "Katsushika Hokusai", 1831),
    "hokusai_bullfinch": ("Bullfinch and Weeping Cherry", "Katsushika Hokusai", 1834),
    "hiroshige_rain": ("Sudden Shower over Shin-Ohashi", "Utagawa Hiroshige", 1857),
    "hiroshige_plum": ("Plum Park in Kameido", "Utagawa Hiroshige", 1857),
    "ophelia": ("Ophelia", "John Everett Millais", 1851),
    "lady_of_shalott": ("The Lady of Shalott", "John William Waterhouse", 1888),
    "waterhouse_miranda": ("Miranda - The Tempest", "John William Waterhouse", 1916),
    "roses_heliogabalus": ("The Roses of Heliogabalus", "Lawrence Alma-Tadema", 1888),
    "bouguereau_shepherdess": ("The Shepherdess", "William-Adolphe Bouguereau", 1889),
    "whistlers_mother": ("Whistler's Mother", "James McNeill Whistler", 1871),
    "bar_folies_bergere": ("A Bar at the Folies-Bergère", "Édouard Manet", 1882),
    "the_fifer": ("The Fifer", "Edouard Manet", 1866),
    "impression_sunrise": ("Impression, Sunrise", "Claude Monet", 1872),
    "water_lilies": ("Water Lilies", "Claude Monet", 1906),
    "rouen_cathedral": ("Rouen Cathedral (Sunset)", "Claude Monet", 1894),
    "poppies": ("Poppy Field", "Claude Monet", 1873),
    "japanese_bridge": ("Water Lilies and Japanese Bridge", "Claude Monet", 1899),
    "dance_moulin": ("Dance at Le Moulin de la Galette", "Pierre-Auguste Renoir", 1876),
    "luncheon_boating": ("Luncheon of the Boating Party", "Pierre-Auguste Renoir", 1881),
    "girl_watering_can": ("A Girl with a Watering Can", "Pierre-Auguste Renoir", 1876),
    "degas_ballet": ("Ballet Rehearsal on Stage", "Edgar Degas", 1874),
    "caillebotte_rainy": ("Paris Street; Rainy Day", "Gustave Caillebotte", 1877),
    "sunday_grande_jatte": ("A Sunday on La Grande Jatte", "Georges Seurat", 1886),
    "bathers_asnieres": ("Bathers at Asnières", "Georges Seurat", 1884),
    "sorolla_seashore": ("Strolling Along the Seashore", "Joaquín Sorolla", 1909),
    "madame_x": ("Madame X", "John Singer Sargent", 1884),
    "gulf_stream": ("The Gulf Stream", "Winslow Homer", 1899),
    "fog_warning": ("The Fog Warning", "Winslow Homer", 1885),
    "nighthawks": ("Nighthawks", "Edward Hopper", 1942),
    "american_gothic": ("American Gothic", "Grant Wood", 1930),
    "starry_night": ("The Starry Night", "Vincent van Gogh", 1889),
    "cafe_terrace": ("Café Terrace at Night", "Vincent van Gogh", 1888),
    "the_bedroom": ("The Bedroom", "Vincent van Gogh", 1888),
    "vangogh_self_portrait": ("Self-Portrait", "Vincent van Gogh", 1889),
    "irises": ("Irises", "Vincent van Gogh", 1889),
    "sunflowers": ("Sunflowers", "Vincent van Gogh", 1888),
    "almond_blossoms": ("Almond Blossoms", "Vincent van Gogh", 1890),
    "wheatfield_cypresses": ("Wheat Field with Cypresses", "Vincent van Gogh", 1889),
    "potato_eaters": ("The Potato Eaters", "Vincent van Gogh", 1885),
    "mont_sainte_victoire": ("Mont Sainte-Victoire", "Paul Cézanne", 1887),
    "card_players": ("The Card Players", "Paul Cézanne", 1895),
    "vision_sermon": ("Vision After the Sermon", "Paul Gauguin", 1888),
    "gauguin_arearea": ("Arearea (The Red Dog)", "Paul Gauguin", 1892),
    "moulin_rouge": ("Moulin Rouge: La Goulue", "Henri de Toulouse-Lautrec", 1891),
    "the_dream_rousseau": ("The Dream", "Henri Rousseau", 1910),
    "sleeping_gypsy": ("The Sleeping Gypsy", "Henri Rousseau", 1897),
    "the_scream": ("The Scream", "Edvard Munch", 1893),
    "munch_karl_johan": ("Evening on Karl Johan", "Edvard Munch", 1892),
    "the_kiss_klimt": ("The Kiss", "Gustav Klimt", 1907),
    "klimt_adele": ("Portrait of Adele Bloch-Bauer I", "Gustav Klimt", 1907),
    "klimt_tree_of_life": ("The Tree of Life", "Gustav Klimt", 1909),
    "mucha_job": ("Job (Cigarettes)", "Alphonse Mucha", 1896),
    "view_of_toledo": ("View of Toledo", "El Greco", 1600),
    "cossacks": ("Reply of the Zaporozhian Cossacks", "Ilya Repin", 1891),
    "harmony_in_red": ("Harmony in Red", "Henri Matisse", 1908),
    "blue_horse": ("Blue Horse I", "Franz Marc", 1911),
    "berlin_street": ("Berlin Street Scene", "Ernst Ludwig Kirchner", 1913),
    "schiele_self_portrait": ("Self-Portrait with Physalis", "Egon Schiele", 1912),
    "modigliani_portrait": ("Jeanne Hébuterne", "Amedeo Modigliani", 1919),
    "composition_viii": ("Composition VIII", "Wassily Kandinsky", 1923),
    "several_circles": ("Several Circles", "Wassily Kandinsky", 1926),
    "black_square": ("Black Square", "Kazimir Malevich", 1915),
    "broadway_boogie": ("Broadway Boogie Woogie", "Piet Mondrian", 1943),
    "white_on_white": ("White on White", "Kazimir Malevich", 1918),
    "woman_parasol": ("Woman with a Parasol", "Claude Monet", 1875),
    "haystacks": ("Haystacks (End of Summer)", "Claude Monet", 1891),
    "morisot_cradle": ("The Cradle", "Berthe Morisot", 1872),
    "cassatt_bath": ("The Child's Bath", "Mary Cassatt", 1893),
    "pissarro_boulevard": ("Boulevard Montmartre", "Camille Pissarro", 1897),
    "delaunay_windows": ("Simultaneous Windows", "Robert Delaunay", 1912),
    "birth_of_venus": ("The Birth of Venus", "Sandro Botticelli", 1485),
    "primavera": ("Primavera", "Sandro Botticelli", 1482),
    "venus_of_urbino": ("Venus of Urbino", "Titian", 1538),
    "bacchus_ariadne": ("Bacchus and Ariadne", "Titian", 1523),
    "virgin_of_rocks": ("Virgin of the Rocks", "Leonardo da Vinci", 1486),
    "last_judgment_michelangelo": ("The Last Judgment", "Michelangelo", 1541),
    "raphael_transfiguration": ("The Transfiguration", "Raphael", 1520),
    "giotto_lamentation": ("Lamentation", "Giotto", 1305),
    "holbein_ambassadors": ("The Ambassadors", "Hans Holbein the Younger", 1533),
    "tintoretto_last_supper": ("The Last Supper", "Tintoretto", 1594),
    "veronese_wedding_cana": ("The Wedding at Cana", "Paolo Veronese", 1563),
    "piero_flagellation": ("The Flagellation of Christ", "Piero della Francesca", 1455),
    "mantegna_dead_christ": ("Lamentation over the Dead Christ", "Andrea Mantegna", 1480),
    "bellini_st_francis": ("St. Francis in the Desert", "Giovanni Bellini", 1480),
    "correggio_assumption": ("Assumption of the Virgin", "Correggio", 1530),
    "cimabue_maesta": ("Maestà", "Cimabue", 1280),
    "duccio_maesta": ("Maestà", "Duccio", 1311),
    "rublev_trinity": ("Trinity", "Andrei Rublev", 1411),
    "van_der_weyden_descent": ("Descent from the Cross", "Rogier van der Weyden", 1435),
    "van_der_goes_portinari": ("Portinari Altarpiece", "Hugo van der Goes", 1475),
    "memling_portrait": ("Portrait of a Young Woman", "Hans Memling", 1480),
    "campin_merode": ("Mérode Altarpiece", "Robert Campin", 1427),
    "velazquez_pope": ("Portrait of Pope Innocent X", "Diego Velázquez", 1650),
    "rembrandt_anatomy": ("The Anatomy Lesson of Dr. Nicolaes Tulp", "Rembrandt", 1632),
    "la_tour_magdalene": ("The Penitent Magdalene", "Georges de La Tour", 1640),
    "guo_xi_early_spring": ("Early Spring", "Guo Xi", 1072),
    "fan_kuan_travelers": ("Travelers Among Mountains and Streams", "Fan Kuan", 1000),
    "zhang_zeduan_qingming": ("Qingming Festival", "Zhang Zeduan", 1100),
    "tohaku_pine_trees": ("Pine Trees", "Hasegawa Tōhaku", 1595),
    "korin_irises": ("Irises", "Ogata Kōrin", 1702),
    "utamaro_beauties": ("Three Beauties of the Present Day", "Kitagawa Utamaro", 1793),
    "sharaku_actor": ("Ōtani Oniji III as Yakko Edobei", "Tōshūsai Sharaku", 1794),
    "reza_abbasi_lovers": ("Two Lovers", "Reza Abbasi", 1630),
    "behzad_yusuf": ("Yusuf and Zulaikha", "Kamāl ud-Dīn Behzād", 1488),
    "fayum_portrait": ("Mummy Portrait of a Young Woman", "Anonymous (Roman Egypt)", 200),
    "nebamun_hunting": ("Nebamun Hunting in the Marshes", "Anonymous (Ancient Egypt)", -1350),
    "nefertari_tomb": ("Nefertari Led by Isis", "Anonymous (Ancient Egypt)", -1255),
    "hunefer_book_dead": ("Book of the Dead of Hunefer", "Anonymous (Ancient Egypt)", -1275),
    "villa_mysteries": ("Villa of the Mysteries", "Anonymous (Roman)", -60),
    "sappho_pompeii": ("Portrait of a Young Woman", "Anonymous (Pompeii)", 55),
    "flora_stabiae": ("Flora", "Anonymous (Stabiae)", 60),
    "alexander_mosaic": ("Alexander Mosaic", "Anonymous (Pompeii)", -100),
    "tres_riches_heures": ("Très Riches Heures (January)", "Limbourg Brothers", 1416),
    "book_of_kells": ("Chi Rho Page", "Anonymous (Insular)", 800),
    "lindisfarne_gospels": ("Carpet Page", "Eadfrith of Lindisfarne", 700),
    "ethiopian_st_george": ("Saint George Icon", "Anonymous (Ethiopian)", 1500),
    "ajanta_padmapani": ("Bodhisattva Padmapani", "Anonymous (Ajanta)", 480),
    "jahangir_portrait": ("Jahangir Preferring a Sufi Shaikh to Kings", "Bichitr", 1620),
    "akbar_court": ("Court of Akbar", "Anonymous (Mughal)", 1590),
    "radha_krishna": ("Radha and Krishna in the Boat of Love", "Anonymous (Rajput)", 1750),
    "ragamala_dhanasri": ("Ragamala: Dhanasri Ragini", "Anonymous (Rajput)", 1690),
    "ottoman_mohacs": ("Battle of Mohács", "Anonymous (Ottoman)", 1588),
    "huizong_cranes": ("Auspicious Cranes", "Emperor Huizong", 1112),
    "night_revels": ("Night Revels of Han Xizai", "Gu Hongzhong", 970),
    "sesshu_haboku": ("Splashed-Ink Landscape", "Sesshū Tōyō", 1495),
    "kim_hongdo_blacksmith": ("Blacksmith Shop", "Kim Hong-do", 1780),
    "jeong_seon_geumgang": ("View of Geumgangsan", "Jeong Seon", 1734),
    "goya_third_may": ("The Third of May 1808", "Francisco Goya", 1814),
    "goya_saturn": ("Saturn Devouring His Son", "Francisco Goya", 1823),
    "canaletto_venice": ("Entrance to the Grand Canal", "Canaletto", 1730),
    "watteau_cythera": ("Embarkation for Cythera", "Antoine Watteau", 1717),
}

try:
    ASSETS_DIR = os.path.join(os.path.dirname(os.path.dirname(
        os.path.abspath(__file__))), "assets", "paintings")
except NameError:
    ASSETS_DIR = ""  # emulator: no local filesystem, uses _PRELOADED

# Max visible chars at 4px/char with 2px left margin on 64px screen
_MAX_CHARS = 15
_CHAR_W = 4
_VISIBLE_W = GRID_SIZE - 4   # usable text width (2px margin each side)
_SCROLL_SPEED = 24            # pixels per second
_SCROLL_PAUSE = 0.6           # seconds before scroll starts
_OVERLAY_DURATION = 4.0       # seconds total
_FADE_TIME = 0.5              # fade-out duration

# Overlay text layout: 3 lines of 5px-tall text with 2px gaps
# Total: 5 + 2 + 5 + 2 + 5 = 19px, plus 1px bottom padding = 20px
_LINE_Y = [GRID_SIZE - 20, GRID_SIZE - 13, GRID_SIZE - 6]  # title, artist, year
_DIM_TOP = _LINE_Y[0] - 3  # start dimming a few px above title


class _PaintingBase(Visual):
    """Base class for painting visuals. Subclasses set _pid."""

    category = "art"
    _pid = ""
    _all_pids = []  # ordered list of all painting IDs, set after class creation

    def reset(self):
        self.pixels = None
        self._show_overlay = False
        self._overlay_alpha = 0.0
        self._overlay_time = 0.0      # how long overlay has been visible
        self._current_pid = self._pid
        self._prev_left = False
        self._prev_right = False
        self._load()

    def _load(self):
        self.pixels = None
        # Emulator mode: decode from pre-loaded base64 atlas
        b64 = _PRELOADED.get(self._current_pid)
        if b64:
            import base64
            d = base64.b64decode(b64)
            S = GRID_SIZE
            self.pixels = [
                [(d[(y * S + x) * 3], d[(y * S + x) * 3 + 1], d[(y * S + x) * 3 + 2])
                 for x in range(S)]
                for y in range(S)
            ]
            return
        # Hardware mode: load PNG via PIL
        if not HAS_PIL:
            return
        path = os.path.join(ASSETS_DIR, f"{self._current_pid}.png")
        if not os.path.exists(path):
            return
        img = Image.open(path).convert("RGB")
        if img.size != (GRID_SIZE, GRID_SIZE):
            img = img.resize((GRID_SIZE, GRID_SIZE), Image.NEAREST)
        self.pixels = [
            [img.getpixel((x, y)) for x in range(GRID_SIZE)]
            for y in range(GRID_SIZE)
        ]

    def handle_input(self, input_state):
        # Left/Right: cycle between paintings (edge-triggered, one per press)
        left_edge = input_state.left and not self._prev_left
        right_edge = input_state.right and not self._prev_right
        self._prev_left = input_state.left
        self._prev_right = input_state.right

        if left_edge or right_edge:
            if self._all_pids:
                try:
                    idx = self._all_pids.index(self._current_pid)
                except ValueError:
                    idx = 0
                if right_edge:
                    idx = (idx + 1) % len(self._all_pids)
                else:
                    idx = (idx - 1) % len(self._all_pids)
                self._current_pid = self._all_pids[idx]
                self._load()
                self._overlay_time = 0.0
            else:
                self._toggle_overlay()
            return True
        if input_state.left or input_state.right:
            return True  # consume held state so menu doesn't see it
        # Up/Down: toggle overlay
        if input_state.up_pressed or input_state.down_pressed:
            self._toggle_overlay()
            return True
        # Action: toggle overlay
        if input_state.action_l or input_state.action_r:
            self._toggle_overlay()
            return True
        return False

    def _toggle_overlay(self):
        self._show_overlay = not self._show_overlay
        if self._show_overlay:
            self._overlay_time = 0.0

    def update(self, dt):
        self.time += dt
        # Smooth fade: alpha approaches target (1.0 if showing, 0.0 if hiding)
        target = 1.0 if self._show_overlay else 0.0
        if self._overlay_alpha < target:
            self._overlay_alpha = min(target, self._overlay_alpha + dt / 0.3)
        elif self._overlay_alpha > target:
            self._overlay_alpha = max(target, self._overlay_alpha - dt / 0.3)
        # Track how long overlay has been visible (for scroll timing)
        if self._overlay_alpha > 0.01:
            self._overlay_time += dt

    def _scroll_text(self, y, text, color):
        """Draw text with bounce-scroll for long strings."""
        text_w = len(text) * _CHAR_W
        if text_w <= _VISIBLE_W:
            self.display.draw_text_small(2, y, text, color)
            return
        # Bounce scroll: pause → scroll right → pause → scroll back → repeat
        max_offset = text_w - _VISIBLE_W
        scroll_time = max_offset / _SCROLL_SPEED  # time to scroll one direction
        cycle = _SCROLL_PAUSE + scroll_time + _SCROLL_PAUSE + scroll_time
        t = self._overlay_time % cycle
        if t < _SCROLL_PAUSE:
            offset = 0
        elif t < _SCROLL_PAUSE + scroll_time:
            offset = int((t - _SCROLL_PAUSE) * _SCROLL_SPEED)
        elif t < _SCROLL_PAUSE + scroll_time + _SCROLL_PAUSE:
            offset = max_offset
        else:
            offset = max_offset - int((t - 2 * _SCROLL_PAUSE - scroll_time) * _SCROLL_SPEED)
        offset = max(0, min(int(max_offset), offset))
        self.display.draw_text_small(2 - offset, y, text, color)

    def draw(self):
        if not self.pixels:
            self.display.clear()
            self.display.draw_text_small(2, 28, "NO IMAGE", Colors.RED)
            return

        # Draw painting
        for y in range(GRID_SIZE):
            for x in range(GRID_SIZE):
                self.display.set_pixel(x, y, self.pixels[y][x])

        # Info overlay (toggle on/off with button)
        alpha = self._overlay_alpha
        if alpha > 0.01:
            # Dim bottom strip with gradient
            for y in range(_DIM_TOP, GRID_SIZE):
                fade = alpha * min(1.0, (y - _DIM_TOP) / 5.0)
                for x in range(GRID_SIZE):
                    r, g, b = self.pixels[y][x]
                    f = 0.7 * fade
                    self.display.set_pixel(x, y, (
                        int(r * (1 - f)),
                        int(g * (1 - f)),
                        int(b * (1 - f)),
                    ))

            # Text lines
            meta = PAINTING_META.get(self._current_pid)
            if meta:
                title, artist, year = meta
                tc = (int(255 * alpha), int(255 * alpha), int(255 * alpha))
                ac = (int(180 * alpha), int(180 * alpha), int(160 * alpha))
                yc = (int(180 * alpha), int(160 * alpha), int(80 * alpha))
                self._scroll_text(_LINE_Y[0], title, tc)
                self._scroll_text(_LINE_Y[1], artist, ac)
                yr_str = f"{abs(year)} BCE" if year < 0 else str(year)
                self.display.draw_text_small(2, _LINE_Y[2], yr_str, yc)


# ── Dynamic class generation ───────────────────────────────────────

PAINTING_VISUALS = []
_all_pids = []

for _pid, (_title, _artist, _year) in PAINTING_META.items():
    if not os.path.exists(os.path.join(ASSETS_DIR, f"{_pid}.png")) and _pid not in _PRELOADED:
        continue
    _all_pids.append(_pid)
    _cls_name = "Painting" + "".join(w.capitalize() for w in _pid.split("_"))
    _cls = type(_cls_name, (_PaintingBase,), {
        "name": _strip_accents(_title).upper(),
        "description": f"{_artist}, {abs(_year)} BCE" if _year < 0 else f"{_artist}, {_year}",
        "_pid": _pid,
    })
    PAINTING_VISUALS.append(_cls)
    globals()[_cls_name] = _cls

# Set the shared ordered list so all paintings can cycle through each other
_PaintingBase._all_pids = _all_pids
