"""
Painting Collection
===================
Auto-generated painting visuals from the LED Arcade painting pipeline.
Each painting appears as its own entry in the ART category.

Controls:
  Left/Right - Cycle between paintings
  Action     - Show info overlay
"""

import os
from . import Visual, Display, Colors, GRID_SIZE

try:
    from PIL import Image
    HAS_PIL = True
except ImportError:
    HAS_PIL = False

# Metadata: pid -> (title, artist, year)
# Generated by: python tools/build_paintings.py --meta
PAINTING_META = {
    "mona_lisa": ("Mona Lisa", "Leonardo da Vinci", 1503),
    "last_supper": ("The Last Supper", "Leonardo da Vinci", 1498),
    "vitruvian_man": ("Vitruvian Man", "Leonardo da Vinci", 1490),
    "birth_of_venus": ("The Birth of Venus", "Sandro Botticelli", 1485),
    "primavera": ("Primavera", "Sandro Botticelli", 1482),
    "creation_of_adam": ("The Creation of Adam", "Michelangelo", 1512),
    "sistine_madonna": ("Sistine Madonna", "Raphael", 1512),
    "school_of_athens": ("The School of Athens", "Raphael", 1511),
    "garden_earthly_delights": ("The Garden of Earthly Delights", "Hieronymus Bosch", 1500),
    "last_judgment_bosch": ("The Last Judgment", "Hieronymus Bosch", 1482),
    "tower_of_babel": ("The Tower of Babel", "Pieter Bruegel", 1563),
    "hunters_snow": ("Hunters in the Snow", "Pieter Bruegel", 1565),
    "arcimboldo_summer": ("Summer", "Giuseppe Arcimboldo", 1563),
    "durer_self_portrait": ("Self-Portrait at Twenty-Eight", "Albrecht Dürer", 1500),
    "arnolfini_portrait": ("The Arnolfini Portrait", "Jan van Eyck", 1434),
    "venus_urbino": ("Venus of Urbino", "Titian", 1538),
    "caravaggio_bacchus": ("Bacchus", "Caravaggio", 1598),
    "caravaggio_judith": ("Judith Beheading Holofernes", "Caravaggio", 1599),
    "calling_st_matthew": ("The Calling of Saint Matthew", "Caravaggio", 1600),
    "caravaggio_medusa": ("Medusa", "Caravaggio", 1597),
    "artemisia_judith": ("Judith Slaying Holofernes", "Artemisia Gentileschi", 1620),
    "girl_pearl_earring": ("Girl with a Pearl Earring", "Johannes Vermeer", 1665),
    "the_milkmaid": ("The Milkmaid", "Johannes Vermeer", 1658),
    "art_of_painting": ("The Art of Painting", "Johannes Vermeer", 1666),
    "girl_reading_letter": ("Girl Reading a Letter by Window", "Johannes Vermeer", 1657),
    "vermeer_astronomer": ("The Astronomer", "Johannes Vermeer", 1668),
    "view_of_delft": ("View of Delft", "Johannes Vermeer", 1661),
    "night_watch": ("The Night Watch", "Rembrandt", 1642),
    "rembrandt_self_portrait": ("Self-Portrait", "Rembrandt", 1660),
    "las_meninas": ("Las Meninas", "Diego Velázquez", 1656),
    "the_swing": ("The Swing", "Jean-Honoré Fragonard", 1767),
    "saturn_devouring": ("Saturn Devouring His Son", "Francisco Goya", 1823),
    "death_of_marat": ("The Death of Marat", "Jacques-Louis David", 1793),
    "napoleon_alps": ("Napoleon Crossing the Alps", "Jacques-Louis David", 1801),
    "wanderer_fog": ("Wanderer Above the Sea of Fog", "Caspar David Friedrich", 1818),
    "liberty_leading": ("Liberty Leading the People", "Eugène Delacroix", 1830),
    "death_sardanapalus": ("The Death of Sardanapalus", "Eugène Delacroix", 1827),
    "raft_of_medusa": ("The Raft of the Medusa", "Théodore Géricault", 1819),
    "epsom_derby": ("The Derby at Epsom", "Théodore Géricault", 1821),
    "fighting_temeraire": ("The Fighting Temeraire", "J.M.W. Turner", 1839),
    "rain_steam_speed": ("Rain, Steam and Speed", "J.M.W. Turner", 1844),
    "hay_wain": ("The Hay Wain", "John Constable", 1821),
    "the_oxbow": ("The Oxbow", "Thomas Cole", 1836),
    "niagara": ("Niagara", "Frederic Edwin Church", 1857),
    "ninth_wave": ("The Ninth Wave", "Ivan Aivazovsky", 1850),
    "great_wave": ("The Great Wave off Kanagawa", "Katsushika Hokusai", 1831),
    "red_fuji": ("Fine Wind, Clear Morning", "Katsushika Hokusai", 1831),
    "hokusai_bullfinch": ("Bullfinch and Weeping Cherry", "Katsushika Hokusai", 1834),
    "hiroshige_rain": ("Sudden Shower over Shin-Ohashi", "Utagawa Hiroshige", 1857),
    "hiroshige_plum": ("Plum Park in Kameido", "Utagawa Hiroshige", 1857),
    "ophelia": ("Ophelia", "John Everett Millais", 1851),
    "lady_of_shalott": ("The Lady of Shalott", "John William Waterhouse", 1888),
    "hylas_nymphs": ("Hylas and the Nymphs", "John William Waterhouse", 1896),
    "nymphs_satyr": ("Nymphs and Satyr", "William-Adolphe Bouguereau", 1873),
    "roses_heliogabalus": ("The Roses of Heliogabalus", "Lawrence Alma-Tadema", 1888),
    "whistlers_mother": ("Whistler's Mother", "James McNeill Whistler", 1871),
    "olympia": ("Olympia", "Édouard Manet", 1863),
    "bar_folies_bergere": ("A Bar at the Folies-Bergère", "Édouard Manet", 1882),
    "impression_sunrise": ("Impression, Sunrise", "Claude Monet", 1872),
    "water_lilies": ("Water Lilies", "Claude Monet", 1906),
    "rouen_cathedral": ("Rouen Cathedral (Sunset)", "Claude Monet", 1894),
    "poppies": ("Poppy Field", "Claude Monet", 1873),
    "japanese_bridge": ("Water Lilies and Japanese Bridge", "Claude Monet", 1899),
    "woman_parasol": ("Woman with a Parasol", "Claude Monet", 1875),
    "haystacks": ("Haystacks (End of Summer)", "Claude Monet", 1891),
    "dance_moulin": ("Dance at Le Moulin de la Galette", "Pierre-Auguste Renoir", 1876),
    "luncheon_boating": ("Luncheon of the Boating Party", "Pierre-Auguste Renoir", 1881),
    "girl_watering_can": ("A Girl with a Watering Can", "Pierre-Auguste Renoir", 1876),
    "degas_ballet": ("Ballet Rehearsal on Stage", "Edgar Degas", 1874),
    "caillebotte_rainy": ("Paris Street; Rainy Day", "Gustave Caillebotte", 1877),
    "morisot_cradle": ("The Cradle", "Berthe Morisot", 1872),
    "cassatt_bath": ("The Child's Bath", "Mary Cassatt", 1893),
    "pissarro_boulevard": ("Boulevard Montmartre", "Camille Pissarro", 1897),
    "sunday_grande_jatte": ("A Sunday on La Grande Jatte", "Georges Seurat", 1886),
    "bathers_asnieres": ("Bathers at Asnières", "Georges Seurat", 1884),
    "sorolla_seashore": ("Strolling Along the Seashore", "Joaquín Sorolla", 1909),
    "madame_x": ("Madame X", "John Singer Sargent", 1884),
    "gulf_stream": ("The Gulf Stream", "Winslow Homer", 1899),
    "fog_warning": ("The Fog Warning", "Winslow Homer", 1885),
    "nighthawks": ("Nighthawks", "Edward Hopper", 1942),
    "american_gothic": ("American Gothic", "Grant Wood", 1930),
    "starry_night": ("The Starry Night", "Vincent van Gogh", 1889),
    "cafe_terrace": ("Café Terrace at Night", "Vincent van Gogh", 1888),
    "the_bedroom": ("The Bedroom", "Vincent van Gogh", 1888),
    "vangogh_self_portrait": ("Self-Portrait", "Vincent van Gogh", 1889),
    "irises": ("Irises", "Vincent van Gogh", 1889),
    "sunflowers": ("Sunflowers", "Vincent van Gogh", 1888),
    "almond_blossoms": ("Almond Blossoms", "Vincent van Gogh", 1890),
    "wheatfield_cypresses": ("Wheat Field with Cypresses", "Vincent van Gogh", 1889),
    "potato_eaters": ("The Potato Eaters", "Vincent van Gogh", 1885),
    "mont_sainte_victoire": ("Mont Sainte-Victoire", "Paul Cézanne", 1887),
    "card_players": ("The Card Players", "Paul Cézanne", 1895),
    "where_do_we_come_from": ("Where Do We Come From?", "Paul Gauguin", 1897),
    "vision_sermon": ("Vision After the Sermon", "Paul Gauguin", 1888),
    "moulin_rouge": ("Moulin Rouge: La Goulue", "Henri de Toulouse-Lautrec", 1891),
    "the_dream_rousseau": ("The Dream", "Henri Rousseau", 1910),
    "sleeping_gypsy": ("The Sleeping Gypsy", "Henri Rousseau", 1897),
    "the_scream": ("The Scream", "Edvard Munch", 1893),
    "munch_madonna": ("Madonna", "Edvard Munch", 1894),
    "the_kiss_klimt": ("The Kiss", "Gustav Klimt", 1907),
    "klimt_adele": ("Portrait of Adele Bloch-Bauer I", "Gustav Klimt", 1907),
    "klimt_tree_of_life": ("The Tree of Life", "Gustav Klimt", 1909),
    "mucha_job": ("Job (Cigarettes)", "Alphonse Mucha", 1896),
    "view_of_toledo": ("View of Toledo", "El Greco", 1600),
    "cossacks": ("Reply of the Zaporozhian Cossacks", "Ilya Repin", 1891),
    "the_dance_matisse": ("The Dance", "Henri Matisse", 1910),
    "blue_horse": ("Blue Horse I", "Franz Marc", 1911),
    "berlin_street": ("Berlin Street Scene", "Ernst Ludwig Kirchner", 1913),
    "schiele_self_portrait": ("Self-Portrait with Physalis", "Egon Schiele", 1912),
    "modigliani_portrait": ("Jeanne Hébuterne", "Amedeo Modigliani", 1919),
    "composition_viii": ("Composition VIII", "Wassily Kandinsky", 1923),
    "several_circles": ("Several Circles", "Wassily Kandinsky", 1926),
    "black_square": ("Black Square", "Kazimir Malevich", 1915),
    "white_on_white": ("White on White", "Kazimir Malevich", 1918),
    "broadway_boogie": ("Broadway Boogie Woogie", "Piet Mondrian", 1943),
    "delaunay_windows": ("Simultaneous Windows", "Robert Delaunay", 1912),
}

ASSETS_DIR = os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))), "assets", "paintings")

# Max visible chars at 4px/char with 2px left margin on 64px screen
_MAX_CHARS = 15
_CHAR_W = 4
_VISIBLE_W = GRID_SIZE - 4   # usable text width (2px margin each side)
_SCROLL_SPEED = 24            # pixels per second
_SCROLL_PAUSE = 0.6           # seconds before scroll starts
_OVERLAY_DURATION = 4.0       # seconds total
_FADE_TIME = 0.5              # fade-out duration

# Overlay text layout: 3 lines of 5px-tall text with 2px gaps
# Total: 5 + 2 + 5 + 2 + 5 = 19px, plus 1px bottom padding = 20px
_LINE_Y = [GRID_SIZE - 20, GRID_SIZE - 13, GRID_SIZE - 6]  # title, artist, year
_DIM_TOP = _LINE_Y[0] - 3  # start dimming a few px above title


class _PaintingBase(Visual):
    """Base class for painting visuals. Subclasses set _pid."""

    category = "art"
    _pid = ""
    _all_pids = []  # ordered list of all painting IDs, set after class creation

    def reset(self):
        self.pixels = None
        self._show_overlay = False
        self._overlay_alpha = 0.0
        self._overlay_time = 0.0      # how long overlay has been visible
        self._current_pid = self._pid
        self._prev_left = False
        self._prev_right = False
        self._load()

    def _load(self):
        self.pixels = None
        if not HAS_PIL:
            return
        path = os.path.join(ASSETS_DIR, f"{self._current_pid}.png")
        if not os.path.exists(path):
            return
        img = Image.open(path).convert("RGB")
        if img.size != (GRID_SIZE, GRID_SIZE):
            img = img.resize((GRID_SIZE, GRID_SIZE), Image.NEAREST)
        self.pixels = [
            [img.getpixel((x, y)) for x in range(GRID_SIZE)]
            for y in range(GRID_SIZE)
        ]

    def handle_input(self, input_state):
        # Left/Right: cycle between paintings (edge-triggered, one per press)
        left_edge = input_state.left and not self._prev_left
        right_edge = input_state.right and not self._prev_right
        self._prev_left = input_state.left
        self._prev_right = input_state.right

        if left_edge or right_edge:
            if self._all_pids:
                try:
                    idx = self._all_pids.index(self._current_pid)
                except ValueError:
                    idx = 0
                if right_edge:
                    idx = (idx + 1) % len(self._all_pids)
                else:
                    idx = (idx - 1) % len(self._all_pids)
                self._current_pid = self._all_pids[idx]
                self._load()
                # Reset scroll position but don't auto-show overlay
                self._overlay_time = 0.0
            return True
        if input_state.left or input_state.right:
            return True  # consume held state so menu doesn't see it
        # Action: toggle info overlay on/off
        if input_state.action_l or input_state.action_r:
            self._show_overlay = not self._show_overlay
            if self._show_overlay:
                self._overlay_time = 0.0
            return True
        return False

    def update(self, dt):
        self.time += dt
        # Smooth fade: alpha approaches target (1.0 if showing, 0.0 if hiding)
        target = 1.0 if self._show_overlay else 0.0
        if self._overlay_alpha < target:
            self._overlay_alpha = min(target, self._overlay_alpha + dt / 0.3)
        elif self._overlay_alpha > target:
            self._overlay_alpha = max(target, self._overlay_alpha - dt / 0.3)
        # Track how long overlay has been visible (for scroll timing)
        if self._overlay_alpha > 0.01:
            self._overlay_time += dt

    def _scroll_text(self, y, text, color):
        """Draw text with auto-scroll for long strings."""
        text_w = len(text) * _CHAR_W
        if text_w <= _VISIBLE_W:
            # Fits — draw static
            self.display.draw_text_small(2, y, text, color)
        else:
            # Scroll: pause, then slide left to reveal full text
            scroll_elapsed = max(0.0, self._overlay_time - _SCROLL_PAUSE)
            offset = int(scroll_elapsed * _SCROLL_SPEED)
            max_offset = text_w - _VISIBLE_W + 8
            offset = min(offset, max_offset)
            self.display.draw_text_small(2 - offset, y, text, color)

    def draw(self):
        if not self.pixels:
            self.display.clear()
            self.display.draw_text_small(2, 28, "NO IMAGE", Colors.RED)
            return

        # Draw painting
        for y in range(GRID_SIZE):
            for x in range(GRID_SIZE):
                self.display.set_pixel(x, y, self.pixels[y][x])

        # Info overlay (toggle on/off with button)
        alpha = self._overlay_alpha
        if alpha > 0.01:
            # Dim bottom strip with gradient
            for y in range(_DIM_TOP, GRID_SIZE):
                fade = alpha * min(1.0, (y - _DIM_TOP) / 5.0)
                for x in range(GRID_SIZE):
                    r, g, b = self.pixels[y][x]
                    f = 0.7 * fade
                    self.display.set_pixel(x, y, (
                        int(r * (1 - f)),
                        int(g * (1 - f)),
                        int(b * (1 - f)),
                    ))

            # Text lines
            meta = PAINTING_META.get(self._current_pid)
            if meta:
                title, artist, year = meta
                tc = (int(255 * alpha), int(255 * alpha), int(255 * alpha))
                ac = (int(180 * alpha), int(180 * alpha), int(160 * alpha))
                yc = (int(180 * alpha), int(160 * alpha), int(80 * alpha))
                self._scroll_text(_LINE_Y[0], title, tc)
                self._scroll_text(_LINE_Y[1], artist, ac)
                self.display.draw_text_small(2, _LINE_Y[2], str(year), yc)


# ── Dynamic class generation ───────────────────────────────────────

PAINTING_VISUALS = []
_all_pids = []

for _pid, (_title, _artist, _year) in PAINTING_META.items():
    if not os.path.exists(os.path.join(ASSETS_DIR, f"{_pid}.png")):
        continue
    _all_pids.append(_pid)
    _cls_name = "Painting" + "".join(w.capitalize() for w in _pid.split("_"))
    _cls = type(_cls_name, (_PaintingBase,), {
        "name": _title.upper(),
        "description": f"{_artist}, {_year}",
        "_pid": _pid,
    })
    PAINTING_VISUALS.append(_cls)
    globals()[_cls_name] = _cls

# Set the shared ordered list so all paintings can cycle through each other
_PaintingBase._all_pids = _all_pids
