"""
MOVE - Human Motion
====================
A stick figure performs various movements, rendered from procedural
biomechanical gait models. 14 joints, 15 bones, with hysteresis
rendering to prevent pixel jitter.

Vitruvian proportions: 8-head figure (48px tall, 6px per head unit).

Controls:
  Left/Right   - Slow down / speed up playback
  Action       - Cycle movement (WALK, RUN, SNEAK, MARCH, IDLE)
"""

from . import Visual, Display, Colors, GRID_SIZE

# --- Pre-baked motion cycles (generated by tools/build_walk.py) ---
# Vitruvian proportions: 48px figure, 6px/head-unit, top_y=8
# fmt: off
WALK_FRAMES = [
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(28,16), 'r_shoulder':(36,16), 'l_elbow':(28,25), 'r_elbow':(36,25), 'l_hand':(30,32), 'r_hand':(39,32), 'l_hip':(29,31), 'r_hip':(35,31), 'l_knee':(26,43), 'r_knee':(40,42), 'l_foot':(19,52), 'r_foot':(45,53)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(28,16), 'r_shoulder':(36,16), 'l_elbow':(28,25), 'r_elbow':(36,25), 'l_hand':(31,32), 'r_hand':(39,33), 'l_hip':(29,31), 'r_hip':(35,31), 'l_knee':(26,43), 'r_knee':(40,42), 'l_foot':(18,52), 'r_foot':(44,53)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(29,25), 'r_elbow':(36,25), 'l_hand':(32,32), 'r_hand':(38,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(27,43), 'r_knee':(40,42), 'l_foot':(18,51), 'r_foot':(43,54)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(29,26), 'r_elbow':(36,26), 'l_hand':(32,32), 'r_hand':(38,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(27,43), 'r_knee':(40,43), 'l_foot':(18,51), 'r_foot':(43,54)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(29,26), 'r_elbow':(35,26), 'l_hand':(33,32), 'r_hand':(38,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(27,43), 'r_knee':(40,43), 'l_foot':(18,51), 'r_foot':(42,55)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(30,26), 'r_elbow':(35,26), 'l_hand':(34,32), 'r_hand':(37,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(27,44), 'r_knee':(39,43), 'l_foot':(18,51), 'r_foot':(41,55)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(30,26), 'r_elbow':(35,26), 'l_hand':(34,32), 'r_hand':(37,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(28,44), 'r_knee':(39,43), 'l_foot':(18,51), 'r_foot':(40,55)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(30,26), 'r_elbow':(34,26), 'l_hand':(34,32), 'r_hand':(37,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(28,44), 'r_knee':(39,44), 'l_foot':(19,51), 'r_foot':(39,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(30,26), 'r_elbow':(34,26), 'l_hand':(35,32), 'r_hand':(36,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(29,44), 'r_knee':(38,44), 'l_foot':(19,51), 'r_foot':(38,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(31,26), 'r_elbow':(34,26), 'l_hand':(35,32), 'r_hand':(36,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(29,44), 'r_knee':(38,44), 'l_foot':(19,51), 'r_foot':(37,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(31,26), 'r_elbow':(34,26), 'l_hand':(35,32), 'r_hand':(36,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(37,44), 'l_foot':(20,51), 'r_foot':(36,56)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(28,18), 'r_shoulder':(36,18), 'l_elbow':(31,26), 'r_elbow':(34,26), 'l_hand':(35,32), 'r_hand':(36,33), 'l_hip':(29,33), 'r_hip':(35,33), 'l_knee':(30,45), 'r_knee':(36,44), 'l_foot':(20,51), 'r_foot':(35,56)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(28,18), 'r_shoulder':(36,18), 'l_elbow':(30,26), 'r_elbow':(34,26), 'l_hand':(35,32), 'r_hand':(36,33), 'l_hip':(29,33), 'r_hip':(35,33), 'l_knee':(30,45), 'r_knee':(36,45), 'l_foot':(21,51), 'r_foot':(34,56)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(28,18), 'r_shoulder':(36,18), 'l_elbow':(30,26), 'r_elbow':(33,26), 'l_hand':(35,32), 'r_hand':(36,33), 'l_hip':(29,33), 'r_hip':(35,33), 'l_knee':(31,44), 'r_knee':(35,45), 'l_foot':(21,51), 'r_foot':(33,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(30,26), 'r_elbow':(33,26), 'l_hand':(35,32), 'r_hand':(36,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(31,44), 'r_knee':(34,44), 'l_foot':(22,52), 'r_foot':(32,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(30,26), 'r_elbow':(33,26), 'l_hand':(34,32), 'r_hand':(36,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(32,44), 'r_knee':(34,44), 'l_foot':(22,52), 'r_foot':(31,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(30,26), 'r_elbow':(34,26), 'l_hand':(34,32), 'r_hand':(36,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(32,44), 'r_knee':(33,44), 'l_foot':(23,52), 'r_foot':(31,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(30,26), 'r_elbow':(34,26), 'l_hand':(34,32), 'r_hand':(36,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(33,44), 'r_knee':(33,44), 'l_foot':(24,52), 'r_foot':(30,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(29,26), 'r_elbow':(34,26), 'l_hand':(33,32), 'r_hand':(36,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(33,43), 'r_knee':(32,44), 'l_foot':(26,53), 'r_foot':(29,55)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(29,26), 'r_elbow':(34,26), 'l_hand':(33,32), 'r_hand':(37,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(33,43), 'r_knee':(32,44), 'l_foot':(28,54), 'r_foot':(29,55)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(29,26), 'r_elbow':(35,26), 'l_hand':(32,32), 'r_hand':(37,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(34,43), 'r_knee':(32,43), 'l_foot':(30,54), 'r_foot':(28,55)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(35,26), 'l_hand':(32,32), 'r_hand':(37,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(34,43), 'r_knee':(32,43), 'l_foot':(33,55), 'r_foot':(26,54)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(28,25), 'r_elbow':(35,25), 'l_hand':(31,32), 'r_hand':(38,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(34,42), 'r_knee':(31,43), 'l_foot':(35,54), 'r_foot':(25,53)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(28,16), 'r_shoulder':(36,16), 'l_elbow':(28,25), 'r_elbow':(36,25), 'l_hand':(31,32), 'r_hand':(38,33), 'l_hip':(29,31), 'r_hip':(35,31), 'l_knee':(34,42), 'r_knee':(31,43), 'l_foot':(37,54), 'r_foot':(25,53)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(28,16), 'r_shoulder':(36,16), 'l_elbow':(28,25), 'r_elbow':(36,25), 'l_hand':(30,32), 'r_hand':(39,32), 'l_hip':(29,31), 'r_hip':(35,31), 'l_knee':(34,42), 'r_knee':(32,43), 'l_foot':(40,53), 'r_foot':(24,52)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(28,16), 'r_shoulder':(36,16), 'l_elbow':(27,25), 'r_elbow':(37,25), 'l_hand':(30,33), 'r_hand':(40,32), 'l_hip':(29,31), 'r_hip':(35,31), 'l_knee':(34,42), 'r_knee':(32,43), 'l_foot':(39,53), 'r_foot':(23,52)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(27,25), 'r_elbow':(37,25), 'l_hand':(30,33), 'r_hand':(40,32), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(34,42), 'r_knee':(32,43), 'l_foot':(38,54), 'r_foot':(23,51)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(27,26), 'r_elbow':(38,26), 'l_hand':(29,33), 'r_hand':(41,32), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(34,43), 'r_knee':(32,43), 'l_foot':(37,54), 'r_foot':(23,51)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(27,26), 'r_elbow':(38,26), 'l_hand':(29,33), 'r_hand':(42,32), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(34,43), 'r_knee':(32,43), 'l_foot':(37,55), 'r_foot':(23,51)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(26,26), 'r_elbow':(38,26), 'l_hand':(29,33), 'r_hand':(42,32), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(34,43), 'r_knee':(33,44), 'l_foot':(36,55), 'r_foot':(23,51)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(26,26), 'r_elbow':(39,26), 'l_hand':(28,33), 'r_hand':(43,32), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(34,43), 'r_knee':(33,44), 'l_foot':(35,55), 'r_foot':(24,51)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(26,26), 'r_elbow':(39,26), 'l_hand':(28,33), 'r_hand':(43,32), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(33,44), 'r_knee':(34,44), 'l_foot':(34,56), 'r_foot':(24,51)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(26,26), 'r_elbow':(39,26), 'l_hand':(28,33), 'r_hand':(43,32), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(33,44), 'r_knee':(34,44), 'l_foot':(33,56), 'r_foot':(24,51)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(25,26), 'r_elbow':(39,26), 'l_hand':(28,33), 'r_hand':(44,32), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(32,44), 'r_knee':(34,44), 'l_foot':(32,56), 'r_foot':(24,51)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(25,26), 'r_elbow':(39,26), 'l_hand':(27,33), 'r_hand':(44,32), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(32,44), 'r_knee':(35,44), 'l_foot':(31,56), 'r_foot':(25,51)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(28,18), 'r_shoulder':(36,18), 'l_elbow':(25,26), 'r_elbow':(39,26), 'l_hand':(27,33), 'r_hand':(44,32), 'l_hip':(29,33), 'r_hip':(35,33), 'l_knee':(31,44), 'r_knee':(35,45), 'l_foot':(30,56), 'r_foot':(25,51)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(28,18), 'r_shoulder':(36,18), 'l_elbow':(25,26), 'r_elbow':(39,26), 'l_hand':(27,33), 'r_hand':(44,32), 'l_hip':(29,33), 'r_hip':(35,33), 'l_knee':(30,45), 'r_knee':(36,45), 'l_foot':(29,56), 'r_foot':(26,51)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(28,18), 'r_shoulder':(36,18), 'l_elbow':(25,26), 'r_elbow':(39,26), 'l_hand':(27,33), 'r_hand':(44,32), 'l_hip':(29,33), 'r_hip':(35,33), 'l_knee':(30,45), 'r_knee':(36,44), 'l_foot':(28,56), 'r_foot':(26,51)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(25,26), 'r_elbow':(39,26), 'l_hand':(27,33), 'r_hand':(43,32), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(29,44), 'r_knee':(37,44), 'l_foot':(27,56), 'r_foot':(27,52)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(25,26), 'r_elbow':(39,26), 'l_hand':(27,33), 'r_hand':(43,32), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(29,44), 'r_knee':(37,44), 'l_foot':(26,56), 'r_foot':(28,52)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(25,26), 'r_elbow':(38,26), 'l_hand':(27,33), 'r_hand':(43,32), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(28,44), 'r_knee':(37,44), 'l_foot':(25,56), 'r_foot':(28,52)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(25,26), 'r_elbow':(38,26), 'l_hand':(27,33), 'r_hand':(42,32), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(27,44), 'r_knee':(38,44), 'l_foot':(25,56), 'r_foot':(29,52)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(25,26), 'r_elbow':(38,26), 'l_hand':(28,33), 'r_hand':(42,32), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(27,44), 'r_knee':(38,43), 'l_foot':(24,55), 'r_foot':(31,53)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(26,26), 'r_elbow':(38,26), 'l_hand':(28,33), 'r_hand':(42,32), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(27,44), 'r_knee':(39,43), 'l_foot':(23,55), 'r_foot':(33,54)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(26,26), 'r_elbow':(37,26), 'l_hand':(28,33), 'r_hand':(41,32), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(26,43), 'r_knee':(39,43), 'l_foot':(22,55), 'r_foot':(36,54)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(26,26), 'r_elbow':(37,26), 'l_hand':(29,33), 'r_hand':(41,32), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(26,43), 'r_knee':(39,43), 'l_foot':(21,54), 'r_foot':(38,55)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(27,25), 'r_elbow':(37,25), 'l_hand':(29,33), 'r_hand':(40,32), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(26,43), 'r_knee':(39,42), 'l_foot':(20,53), 'r_foot':(40,54)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(28,16), 'r_shoulder':(36,16), 'l_elbow':(27,25), 'r_elbow':(37,25), 'l_hand':(30,33), 'r_hand':(39,32), 'l_hip':(29,31), 'r_hip':(35,31), 'l_knee':(26,43), 'r_knee':(40,42), 'l_foot':(19,53), 'r_foot':(42,54)},
]
RUN_FRAMES = [
    {'head':(32,9), 'neck':(32,12), 'l_shoulder':(28,15), 'r_shoulder':(36,15), 'l_elbow':(28,24), 'r_elbow':(36,24), 'l_hand':(33,30), 'r_hand':(42,30), 'l_hip':(29,30), 'r_hip':(35,30), 'l_knee':(24,41), 'r_knee':(43,39), 'l_foot':(14,48), 'r_foot':(52,47)},
    {'head':(32,9), 'neck':(32,12), 'l_shoulder':(28,15), 'r_shoulder':(36,15), 'l_elbow':(29,24), 'r_elbow':(35,24), 'l_hand':(35,29), 'r_hand':(40,30), 'l_hip':(29,30), 'r_hip':(35,30), 'l_knee':(25,41), 'r_knee':(43,39), 'l_foot':(14,46), 'r_foot':(50,49)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(28,16), 'r_shoulder':(36,16), 'l_elbow':(30,25), 'r_elbow':(34,25), 'l_hand':(36,28), 'r_hand':(39,30), 'l_hip':(30,31), 'r_hip':(35,31), 'l_knee':(25,42), 'r_knee':(43,40), 'l_foot':(14,46), 'r_foot':(49,50)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(28,16), 'r_shoulder':(37,16), 'l_elbow':(31,25), 'r_elbow':(34,25), 'l_hand':(38,28), 'r_hand':(38,31), 'l_hip':(30,31), 'r_hip':(35,31), 'l_knee':(26,43), 'r_knee':(42,41), 'l_foot':(14,46), 'r_foot':(47,52)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(32,25), 'r_elbow':(33,25), 'l_hand':(39,28), 'r_hand':(37,31), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(27,44), 'r_knee':(42,42), 'l_foot':(15,47), 'r_foot':(45,53)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(28,18), 'r_shoulder':(37,18), 'l_elbow':(32,26), 'r_elbow':(32,26), 'l_hand':(39,28), 'r_hand':(37,32), 'l_hip':(30,33), 'r_hip':(35,33), 'l_knee':(28,44), 'r_knee':(41,43), 'l_foot':(16,47), 'r_foot':(43,55)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(28,18), 'r_shoulder':(36,18), 'l_elbow':(33,26), 'r_elbow':(32,26), 'l_hand':(40,27), 'r_hand':(36,32), 'l_hip':(30,33), 'r_hip':(35,33), 'l_knee':(29,45), 'r_knee':(40,44), 'l_foot':(17,48), 'r_foot':(41,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(33,26), 'r_elbow':(31,26), 'l_hand':(40,27), 'r_hand':(36,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(30,46), 'r_knee':(38,45), 'l_foot':(19,49), 'r_foot':(38,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(33,26), 'r_elbow':(31,26), 'l_hand':(40,27), 'r_hand':(35,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(31,45), 'r_knee':(37,45), 'l_foot':(20,49), 'r_foot':(36,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(33,26), 'r_elbow':(31,26), 'l_hand':(40,27), 'r_hand':(35,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(33,45), 'r_knee':(35,46), 'l_foot':(21,49), 'r_foot':(33,57)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(28,18), 'r_shoulder':(36,18), 'l_elbow':(32,26), 'r_elbow':(31,26), 'l_hand':(40,27), 'r_hand':(36,32), 'l_hip':(29,33), 'r_hip':(34,33), 'l_knee':(34,44), 'r_knee':(34,45), 'l_foot':(23,49), 'r_foot':(31,57)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(27,18), 'r_shoulder':(36,18), 'l_elbow':(32,26), 'r_elbow':(32,26), 'l_hand':(39,28), 'r_hand':(36,32), 'l_hip':(29,33), 'r_hip':(34,33), 'l_knee':(35,43), 'r_knee':(32,44), 'l_foot':(25,49), 'r_foot':(29,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(31,25), 'r_elbow':(32,25), 'l_hand':(38,28), 'r_hand':(37,31), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(36,42), 'r_knee':(31,44), 'l_foot':(28,51), 'r_foot':(27,55)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(27,16), 'r_shoulder':(36,16), 'l_elbow':(30,25), 'r_elbow':(33,25), 'l_hand':(37,28), 'r_hand':(38,31), 'l_hip':(29,31), 'r_hip':(34,31), 'l_knee':(37,41), 'r_knee':(30,43), 'l_foot':(33,52), 'r_foot':(25,54)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(28,16), 'r_shoulder':(36,16), 'l_elbow':(30,25), 'r_elbow':(34,25), 'l_hand':(36,28), 'r_hand':(39,30), 'l_hip':(29,31), 'r_hip':(34,31), 'l_knee':(37,40), 'r_knee':(30,42), 'l_foot':(38,52), 'r_foot':(23,51)},
    {'head':(32,9), 'neck':(32,12), 'l_shoulder':(28,15), 'r_shoulder':(36,15), 'l_elbow':(29,24), 'r_elbow':(35,24), 'l_hand':(35,29), 'r_hand':(40,30), 'l_hip':(29,30), 'r_hip':(35,30), 'l_knee':(38,39), 'r_knee':(30,41), 'l_foot':(42,50), 'r_foot':(21,49)},
    {'head':(32,9), 'neck':(32,12), 'l_shoulder':(28,15), 'r_shoulder':(36,15), 'l_elbow':(28,24), 'r_elbow':(36,24), 'l_hand':(33,30), 'r_hand':(42,30), 'l_hip':(29,30), 'r_hip':(35,30), 'l_knee':(38,39), 'r_knee':(30,41), 'l_foot':(46,47), 'r_foot':(20,48)},
    {'head':(32,9), 'neck':(32,12), 'l_shoulder':(28,15), 'r_shoulder':(36,15), 'l_elbow':(27,24), 'r_elbow':(37,24), 'l_hand':(32,30), 'r_hand':(43,29), 'l_hip':(29,30), 'r_hip':(35,30), 'l_knee':(38,39), 'r_knee':(30,41), 'l_foot':(45,49), 'r_foot':(19,46)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(28,16), 'r_shoulder':(36,16), 'l_elbow':(26,25), 'r_elbow':(39,25), 'l_hand':(31,30), 'r_hand':(45,28), 'l_hip':(30,31), 'r_hip':(35,31), 'l_knee':(38,40), 'r_knee':(30,42), 'l_foot':(44,50), 'r_foot':(19,46)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(28,16), 'r_shoulder':(37,16), 'l_elbow':(25,25), 'r_elbow':(40,25), 'l_hand':(30,31), 'r_hand':(46,28), 'l_hip':(30,31), 'r_hip':(35,31), 'l_knee':(37,41), 'r_knee':(31,43), 'l_foot':(42,52), 'r_foot':(19,46)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(24,25), 'r_elbow':(40,25), 'l_hand':(29,31), 'r_hand':(47,28), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(36,42), 'r_knee':(32,44), 'l_foot':(40,53), 'r_foot':(20,47)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(28,18), 'r_shoulder':(37,18), 'l_elbow':(24,26), 'r_elbow':(41,26), 'l_hand':(28,32), 'r_hand':(48,28), 'l_hip':(30,33), 'r_hip':(35,33), 'l_knee':(35,43), 'r_knee':(33,44), 'l_foot':(38,55), 'r_foot':(21,47)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(28,18), 'r_shoulder':(36,18), 'l_elbow':(23,26), 'r_elbow':(41,26), 'l_hand':(27,32), 'r_hand':(49,27), 'l_hip':(30,33), 'r_hip':(35,33), 'l_knee':(34,44), 'r_knee':(34,45), 'l_foot':(35,56), 'r_foot':(22,48)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(23,26), 'r_elbow':(41,26), 'l_hand':(27,32), 'r_hand':(49,27), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(33,45), 'r_knee':(35,46), 'l_foot':(33,57), 'r_foot':(24,49)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(23,26), 'r_elbow':(41,26), 'l_hand':(27,32), 'r_hand':(49,27), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(31,45), 'r_knee':(37,45), 'l_foot':(31,57), 'r_foot':(25,49)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(23,26), 'r_elbow':(41,26), 'l_hand':(27,32), 'r_hand':(49,27), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(30,46), 'r_knee':(38,45), 'l_foot':(28,57), 'r_foot':(27,49)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(28,18), 'r_shoulder':(36,18), 'l_elbow':(23,26), 'r_elbow':(41,26), 'l_hand':(27,32), 'r_hand':(48,27), 'l_hip':(29,33), 'r_hip':(34,33), 'l_knee':(28,45), 'r_knee':(39,44), 'l_foot':(26,57), 'r_foot':(28,49)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(27,18), 'r_shoulder':(36,18), 'l_elbow':(23,26), 'r_elbow':(40,26), 'l_hand':(28,32), 'r_hand':(48,28), 'l_hip':(29,33), 'r_hip':(34,33), 'l_knee':(27,44), 'r_knee':(40,43), 'l_foot':(23,56), 'r_foot':(30,49)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(24,25), 'r_elbow':(40,25), 'l_hand':(28,31), 'r_hand':(47,28), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(26,44), 'r_knee':(41,42), 'l_foot':(22,55), 'r_foot':(33,51)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(27,16), 'r_shoulder':(36,16), 'l_elbow':(24,25), 'r_elbow':(39,25), 'l_hand':(29,31), 'r_hand':(46,28), 'l_hip':(29,31), 'r_hip':(34,31), 'l_knee':(25,43), 'r_knee':(42,41), 'l_foot':(20,54), 'r_foot':(38,52)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(28,16), 'r_shoulder':(36,16), 'l_elbow':(25,25), 'r_elbow':(38,25), 'l_hand':(30,30), 'r_hand':(45,28), 'l_hip':(29,31), 'r_hip':(34,31), 'l_knee':(25,42), 'r_knee':(43,40), 'l_foot':(17,51), 'r_foot':(43,52)},
    {'head':(32,9), 'neck':(32,12), 'l_shoulder':(28,15), 'r_shoulder':(36,15), 'l_elbow':(27,24), 'r_elbow':(37,24), 'l_hand':(32,30), 'r_hand':(43,29), 'l_hip':(29,30), 'r_hip':(35,30), 'l_knee':(24,41), 'r_knee':(43,39), 'l_foot':(15,49), 'r_foot':(47,50)},
]
SNEAK_FRAMES = [
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(33,33), 'r_hand':(42,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(29,46), 'r_knee':(39,45), 'l_foot':(24,57), 'r_foot':(43,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(34,33), 'r_hand':(42,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(29,46), 'r_knee':(39,45), 'l_foot':(24,57), 'r_foot':(42,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(34,32), 'r_hand':(42,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(29,46), 'r_knee':(39,45), 'l_foot':(23,56), 'r_foot':(41,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(34,32), 'r_hand':(42,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(29,46), 'r_knee':(39,45), 'l_foot':(23,56), 'r_foot':(40,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(34,32), 'r_hand':(42,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(29,46), 'r_knee':(39,45), 'l_foot':(23,56), 'r_foot':(39,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(34,32), 'r_hand':(42,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(29,46), 'r_knee':(39,45), 'l_foot':(23,56), 'r_foot':(39,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(34,32), 'r_hand':(42,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(29,46), 'r_knee':(38,45), 'l_foot':(23,56), 'r_foot':(38,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(34,32), 'r_hand':(42,33), 'l_hip':(30,34), 'r_hip':(35,34), 'l_knee':(29,46), 'r_knee':(38,45), 'l_foot':(23,56), 'r_foot':(37,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(34,32), 'r_hand':(42,33), 'l_hip':(30,34), 'r_hip':(35,34), 'l_knee':(29,46), 'r_knee':(38,45), 'l_foot':(23,56), 'r_foot':(37,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(34,32), 'r_hand':(42,33), 'l_hip':(30,34), 'r_hip':(35,34), 'l_knee':(30,46), 'r_knee':(38,46), 'l_foot':(23,56), 'r_foot':(36,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(35,32), 'r_hand':(42,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(30,46), 'r_knee':(38,46), 'l_foot':(23,56), 'r_foot':(36,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(35,32), 'r_hand':(41,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(30,46), 'r_knee':(38,46), 'l_foot':(24,56), 'r_foot':(36,58)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(29,28), 'r_elbow':(36,28), 'l_hand':(35,32), 'r_hand':(41,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(30,46), 'r_knee':(37,46), 'l_foot':(24,56), 'r_foot':(35,58)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(29,28), 'r_elbow':(36,28), 'l_hand':(35,32), 'r_hand':(41,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(30,46), 'r_knee':(37,46), 'l_foot':(24,56), 'r_foot':(35,58)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(29,28), 'r_elbow':(36,28), 'l_hand':(35,32), 'r_hand':(41,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(31,46), 'r_knee':(37,46), 'l_foot':(24,56), 'r_foot':(35,58)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(35,32), 'r_hand':(41,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(31,46), 'r_knee':(37,46), 'l_foot':(24,56), 'r_foot':(35,58)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(35,32), 'r_hand':(41,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(31,46), 'r_knee':(36,46), 'l_foot':(24,56), 'r_foot':(34,58)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(35,32), 'r_hand':(41,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(31,46), 'r_knee':(36,46), 'l_foot':(25,56), 'r_foot':(34,58)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(35,28), 'l_hand':(35,32), 'r_hand':(41,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(31,46), 'r_knee':(36,46), 'l_foot':(25,56), 'r_foot':(34,58)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(35,28), 'l_hand':(34,32), 'r_hand':(41,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(32,46), 'r_knee':(36,46), 'l_foot':(25,56), 'r_foot':(34,58)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(35,28), 'l_hand':(34,32), 'r_hand':(41,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(32,46), 'r_knee':(35,46), 'l_foot':(26,56), 'r_foot':(33,58)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(34,32), 'r_hand':(41,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(32,46), 'r_knee':(35,46), 'l_foot':(26,56), 'r_foot':(33,58)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(34,32), 'r_hand':(41,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(32,46), 'r_knee':(35,46), 'l_foot':(26,56), 'r_foot':(33,58)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(34,32), 'r_hand':(41,33), 'l_hip':(29,34), 'r_hip':(34,34), 'l_knee':(32,46), 'r_knee':(35,46), 'l_foot':(27,56), 'r_foot':(33,58)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(34,32), 'r_hand':(41,33), 'l_hip':(29,34), 'r_hip':(34,34), 'l_knee':(33,45), 'r_knee':(34,46), 'l_foot':(28,57), 'r_foot':(33,58)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(34,32), 'r_hand':(41,33), 'l_hip':(29,34), 'r_hip':(34,34), 'l_knee':(33,45), 'r_knee':(34,46), 'l_foot':(29,57), 'r_foot':(33,58)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(34,32), 'r_hand':(41,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(33,45), 'r_knee':(34,46), 'l_foot':(30,57), 'r_foot':(32,58)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(34,32), 'r_hand':(42,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(33,45), 'r_knee':(34,46), 'l_foot':(32,57), 'r_foot':(32,58)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(34,32), 'r_hand':(42,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(33,45), 'r_knee':(34,46), 'l_foot':(33,57), 'r_foot':(31,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(34,32), 'r_hand':(42,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(33,45), 'r_knee':(34,46), 'l_foot':(34,57), 'r_foot':(31,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(34,32), 'r_hand':(42,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(33,45), 'r_knee':(34,46), 'l_foot':(35,57), 'r_foot':(30,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(34,33), 'r_hand':(42,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(33,45), 'r_knee':(34,46), 'l_foot':(36,57), 'r_foot':(30,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(33,33), 'r_hand':(42,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(33,45), 'r_knee':(34,46), 'l_foot':(38,56), 'r_foot':(29,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(33,33), 'r_hand':(42,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(33,45), 'r_knee':(34,46), 'l_foot':(37,57), 'r_foot':(29,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(42,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(33,45), 'r_knee':(34,46), 'l_foot':(36,57), 'r_foot':(29,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(42,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(33,45), 'r_knee':(34,46), 'l_foot':(35,57), 'r_foot':(28,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(33,45), 'r_knee':(34,46), 'l_foot':(34,57), 'r_foot':(28,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(33,45), 'r_knee':(34,46), 'l_foot':(33,57), 'r_foot':(28,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(33,45), 'r_knee':(34,46), 'l_foot':(33,57), 'r_foot':(28,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(30,34), 'r_hip':(35,34), 'l_knee':(33,45), 'r_knee':(35,46), 'l_foot':(32,57), 'r_foot':(29,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(30,34), 'r_hip':(35,34), 'l_knee':(33,45), 'r_knee':(35,46), 'l_foot':(31,57), 'r_foot':(29,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(30,34), 'r_hip':(35,34), 'l_knee':(33,46), 'r_knee':(35,46), 'l_foot':(31,57), 'r_foot':(29,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(33,46), 'r_knee':(35,46), 'l_foot':(30,57), 'r_foot':(29,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(32,46), 'r_knee':(35,46), 'l_foot':(30,58), 'r_foot':(29,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(32,46), 'r_knee':(35,46), 'l_foot':(30,58), 'r_foot':(29,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(32,46), 'r_knee':(36,46), 'l_foot':(30,58), 'r_foot':(29,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(32,46), 'r_knee':(36,46), 'l_foot':(30,58), 'r_foot':(29,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(31,46), 'r_knee':(36,46), 'l_foot':(29,58), 'r_foot':(29,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(31,46), 'r_knee':(36,46), 'l_foot':(29,58), 'r_foot':(30,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(31,46), 'r_knee':(37,46), 'l_foot':(29,58), 'r_foot':(30,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(30,46), 'r_knee':(37,46), 'l_foot':(29,58), 'r_foot':(30,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(30,46), 'r_knee':(37,46), 'l_foot':(28,58), 'r_foot':(30,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(30,46), 'r_knee':(37,46), 'l_foot':(28,58), 'r_foot':(31,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(30,46), 'r_knee':(37,46), 'l_foot':(28,58), 'r_foot':(31,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(30,46), 'r_knee':(38,46), 'l_foot':(28,58), 'r_foot':(31,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(29,34), 'r_hip':(34,34), 'l_knee':(29,46), 'r_knee':(38,46), 'l_foot':(28,58), 'r_foot':(32,56)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(29,34), 'r_hip':(34,34), 'l_knee':(29,46), 'r_knee':(38,45), 'l_foot':(28,58), 'r_foot':(33,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(29,34), 'r_hip':(34,34), 'l_knee':(29,46), 'r_knee':(38,45), 'l_foot':(27,58), 'r_foot':(35,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(29,46), 'r_knee':(38,45), 'l_foot':(27,58), 'r_foot':(36,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(43,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(29,46), 'r_knee':(38,45), 'l_foot':(27,58), 'r_foot':(37,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(37,28), 'l_hand':(33,33), 'r_hand':(42,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(29,46), 'r_knee':(38,45), 'l_foot':(26,57), 'r_foot':(38,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(36,28), 'l_hand':(33,33), 'r_hand':(42,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(29,46), 'r_knee':(39,45), 'l_foot':(25,57), 'r_foot':(39,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(27,28), 'r_elbow':(36,28), 'l_hand':(33,33), 'r_hand':(42,32), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(29,46), 'r_knee':(39,45), 'l_foot':(25,57), 'r_foot':(40,57)},
    {'head':(32,13), 'neck':(32,16), 'l_shoulder':(28,19), 'r_shoulder':(36,19), 'l_elbow':(28,28), 'r_elbow':(36,28), 'l_hand':(33,33), 'r_hand':(42,33), 'l_hip':(29,34), 'r_hip':(35,34), 'l_knee':(29,46), 'r_knee':(39,45), 'l_foot':(24,57), 'r_foot':(41,57)},
]
MARCH_FRAMES = [
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(28,16), 'r_shoulder':(36,16), 'l_elbow':(28,25), 'r_elbow':(36,25), 'l_hand':(34,30), 'r_hand':(42,30), 'l_hip':(29,31), 'r_hip':(35,31), 'l_knee':(24,42), 'r_knee':(41,41), 'l_foot':(14,48), 'r_foot':(48,51)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(28,16), 'r_shoulder':(36,16), 'l_elbow':(29,25), 'r_elbow':(36,25), 'l_hand':(35,29), 'r_hand':(42,30), 'l_hip':(30,31), 'r_hip':(35,31), 'l_knee':(24,42), 'r_knee':(41,41), 'l_foot':(13,47), 'r_foot':(47,52)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(28,16), 'r_shoulder':(37,16), 'l_elbow':(29,25), 'r_elbow':(35,25), 'l_hand':(36,29), 'r_hand':(41,30), 'l_hip':(30,31), 'r_hip':(35,31), 'l_knee':(24,42), 'r_knee':(41,42), 'l_foot':(13,47), 'r_foot':(47,52)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(30,25), 'r_elbow':(35,25), 'l_hand':(37,28), 'r_hand':(40,31), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(25,43), 'r_knee':(41,42), 'l_foot':(13,46), 'r_foot':(46,53)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(31,25), 'r_elbow':(34,25), 'l_hand':(38,28), 'r_hand':(39,31), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(25,43), 'r_knee':(41,42), 'l_foot':(14,47), 'r_foot':(44,54)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(31,25), 'r_elbow':(34,25), 'l_hand':(39,27), 'r_hand':(38,31), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(26,43), 'r_knee':(40,43), 'l_foot':(15,47), 'r_foot':(43,55)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(32,25), 'r_elbow':(33,25), 'l_hand':(39,27), 'r_hand':(38,31), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(27,44), 'r_knee':(39,43), 'l_foot':(15,47), 'r_foot':(42,55)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(32,25), 'r_elbow':(33,25), 'l_hand':(40,27), 'r_hand':(37,31), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(28,44), 'r_knee':(38,44), 'l_foot':(16,47), 'r_foot':(40,56)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(28,18), 'r_shoulder':(37,18), 'l_elbow':(32,25), 'r_elbow':(32,25), 'l_hand':(40,26), 'r_hand':(37,32), 'l_hip':(30,33), 'r_hip':(35,33), 'l_knee':(28,45), 'r_knee':(37,44), 'l_foot':(17,47), 'r_foot':(38,56)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(28,18), 'r_shoulder':(36,18), 'l_elbow':(32,26), 'r_elbow':(32,26), 'l_hand':(40,26), 'r_hand':(36,32), 'l_hip':(30,33), 'r_hip':(35,33), 'l_knee':(29,45), 'r_knee':(36,45), 'l_foot':(17,47), 'r_foot':(36,57)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(28,18), 'r_shoulder':(36,18), 'l_elbow':(32,26), 'r_elbow':(32,26), 'l_hand':(40,26), 'r_hand':(36,32), 'l_hip':(29,33), 'r_hip':(35,33), 'l_knee':(30,45), 'r_knee':(35,45), 'l_foot':(18,48), 'r_foot':(34,57)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(28,18), 'r_shoulder':(36,18), 'l_elbow':(32,26), 'r_elbow':(32,26), 'l_hand':(39,26), 'r_hand':(36,32), 'l_hip':(29,33), 'r_hip':(34,33), 'l_knee':(31,45), 'r_knee':(34,45), 'l_foot':(19,48), 'r_foot':(32,57)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(27,18), 'r_shoulder':(36,18), 'l_elbow':(32,25), 'r_elbow':(32,25), 'l_hand':(39,26), 'r_hand':(36,32), 'l_hip':(29,33), 'r_hip':(34,33), 'l_knee':(32,44), 'r_knee':(33,45), 'l_foot':(20,48), 'r_foot':(30,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(31,25), 'r_elbow':(32,25), 'l_hand':(39,27), 'r_hand':(36,31), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(32,44), 'r_knee':(32,44), 'l_foot':(21,48), 'r_foot':(29,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(31,25), 'r_elbow':(32,25), 'l_hand':(38,27), 'r_hand':(37,31), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(33,43), 'r_knee':(31,44), 'l_foot':(22,49), 'r_foot':(27,55)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(30,25), 'r_elbow':(33,25), 'l_hand':(38,27), 'r_hand':(37,31), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(34,43), 'r_knee':(30,43), 'l_foot':(25,51), 'r_foot':(26,54)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(30,25), 'r_elbow':(33,25), 'l_hand':(37,28), 'r_hand':(38,31), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(34,42), 'r_knee':(30,43), 'l_foot':(28,53), 'r_foot':(25,54)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(29,25), 'r_elbow':(34,25), 'l_hand':(36,28), 'r_hand':(39,31), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(35,42), 'r_knee':(29,43), 'l_foot':(32,54), 'r_foot':(23,52)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(27,16), 'r_shoulder':(36,16), 'l_elbow':(29,25), 'r_elbow':(35,25), 'l_hand':(36,29), 'r_hand':(40,30), 'l_hip':(29,31), 'r_hip':(34,31), 'l_knee':(35,42), 'r_knee':(29,42), 'l_foot':(35,54), 'r_foot':(21,51)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(28,16), 'r_shoulder':(36,16), 'l_elbow':(28,25), 'r_elbow':(35,25), 'l_hand':(35,29), 'r_hand':(41,30), 'l_hip':(29,31), 'r_hip':(34,31), 'l_knee':(36,41), 'r_knee':(29,42), 'l_foot':(39,53), 'r_foot':(20,50)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(28,16), 'r_shoulder':(36,16), 'l_elbow':(28,25), 'r_elbow':(36,25), 'l_hand':(34,30), 'r_hand':(42,30), 'l_hip':(29,31), 'r_hip':(35,31), 'l_knee':(36,41), 'r_knee':(29,42), 'l_foot':(42,51), 'r_foot':(19,48)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(28,16), 'r_shoulder':(36,16), 'l_elbow':(27,25), 'r_elbow':(37,25), 'l_hand':(33,30), 'r_hand':(44,29), 'l_hip':(30,31), 'r_hip':(35,31), 'l_knee':(36,41), 'r_knee':(29,42), 'l_foot':(42,52), 'r_foot':(19,47)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(28,16), 'r_shoulder':(37,16), 'l_elbow':(27,25), 'r_elbow':(38,25), 'l_hand':(32,30), 'r_hand':(45,29), 'l_hip':(30,31), 'r_hip':(35,31), 'l_knee':(36,42), 'r_knee':(30,42), 'l_foot':(41,52), 'r_foot':(19,47)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(26,25), 'r_elbow':(39,25), 'l_hand':(31,31), 'r_hand':(46,28), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(36,42), 'r_knee':(30,43), 'l_foot':(40,53), 'r_foot':(19,46)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(25,25), 'r_elbow':(40,25), 'l_hand':(31,31), 'r_hand':(47,28), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(35,42), 'r_knee':(31,43), 'l_foot':(39,54), 'r_foot':(19,47)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(25,25), 'r_elbow':(40,25), 'l_hand':(30,31), 'r_hand':(47,27), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(35,43), 'r_knee':(31,43), 'l_foot':(38,55), 'r_foot':(20,47)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(24,25), 'r_elbow':(40,25), 'l_hand':(29,31), 'r_hand':(48,27), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(34,43), 'r_knee':(32,44), 'l_foot':(36,55), 'r_foot':(20,47)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(24,25), 'r_elbow':(41,25), 'l_hand':(29,31), 'r_hand':(48,27), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(33,44), 'r_knee':(33,44), 'l_foot':(35,56), 'r_foot':(21,47)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(28,18), 'r_shoulder':(37,18), 'l_elbow':(24,25), 'r_elbow':(41,25), 'l_hand':(28,32), 'r_hand':(48,26), 'l_hip':(30,33), 'r_hip':(35,33), 'l_knee':(32,44), 'r_knee':(34,45), 'l_foot':(33,56), 'r_foot':(22,47)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(28,18), 'r_shoulder':(36,18), 'l_elbow':(23,26), 'r_elbow':(41,26), 'l_hand':(28,32), 'r_hand':(48,26), 'l_hip':(30,33), 'r_hip':(35,33), 'l_knee':(31,45), 'r_knee':(34,45), 'l_foot':(31,57), 'r_foot':(23,47)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(28,18), 'r_shoulder':(36,18), 'l_elbow':(23,26), 'r_elbow':(41,26), 'l_hand':(27,32), 'r_hand':(48,26), 'l_hip':(29,33), 'r_hip':(35,33), 'l_knee':(30,45), 'r_knee':(35,45), 'l_foot':(29,57), 'r_foot':(24,48)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(28,18), 'r_shoulder':(36,18), 'l_elbow':(23,26), 'r_elbow':(41,26), 'l_hand':(27,32), 'r_hand':(48,26), 'l_hip':(29,33), 'r_hip':(34,33), 'l_knee':(29,45), 'r_knee':(36,45), 'l_foot':(27,57), 'r_foot':(25,48)},
    {'head':(32,12), 'neck':(32,15), 'l_shoulder':(27,18), 'r_shoulder':(36,18), 'l_elbow':(23,25), 'r_elbow':(40,25), 'l_hand':(28,32), 'r_hand':(48,26), 'l_hip':(29,33), 'r_hip':(34,33), 'l_knee':(28,45), 'r_knee':(37,44), 'l_foot':(25,56), 'r_foot':(26,48)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(23,25), 'r_elbow':(40,25), 'l_hand':(28,31), 'r_hand':(47,27), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(27,44), 'r_knee':(38,44), 'l_foot':(23,56), 'r_foot':(27,48)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(24,25), 'r_elbow':(40,25), 'l_hand':(28,31), 'r_hand':(47,27), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(26,44), 'r_knee':(38,43), 'l_foot':(22,55), 'r_foot':(28,49)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(24,25), 'r_elbow':(39,25), 'l_hand':(29,31), 'r_hand':(46,27), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(25,43), 'r_knee':(39,43), 'l_foot':(20,54), 'r_foot':(30,51)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(24,25), 'r_elbow':(39,25), 'l_hand':(30,31), 'r_hand':(46,28), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(25,43), 'r_knee':(40,42), 'l_foot':(19,54), 'r_foot':(33,53)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(25,25), 'r_elbow':(38,25), 'l_hand':(31,31), 'r_hand':(45,28), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(24,43), 'r_knee':(40,42), 'l_foot':(17,52), 'r_foot':(37,54)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(27,16), 'r_shoulder':(36,16), 'l_elbow':(26,25), 'r_elbow':(37,25), 'l_hand':(32,30), 'r_hand':(44,29), 'l_hip':(29,31), 'r_hip':(34,31), 'l_knee':(24,42), 'r_knee':(41,42), 'l_foot':(16,51), 'r_foot':(41,54)},
    {'head':(32,10), 'neck':(32,13), 'l_shoulder':(28,16), 'r_shoulder':(36,16), 'l_elbow':(27,25), 'r_elbow':(37,25), 'l_hand':(33,30), 'r_hand':(43,29), 'l_hip':(29,31), 'r_hip':(34,31), 'l_knee':(24,42), 'r_knee':(41,41), 'l_foot':(15,50), 'r_foot':(44,53)},
]
IDLE_FRAMES = [
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(38,33), 'l_hip':(29,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(38,33), 'l_hip':(29,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(38,33), 'l_hip':(29,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(30,33), 'r_hand':(39,33), 'l_hip':(29,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(30,33), 'r_hand':(39,33), 'l_hip':(29,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(29,33), 'r_hand':(39,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(29,33), 'r_hand':(39,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(29,33), 'r_hand':(39,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(29,33), 'r_hand':(39,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(29,33), 'r_hand':(39,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(29,33), 'r_hand':(39,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(29,33), 'r_hand':(39,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(29,33), 'r_hand':(39,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(29,33), 'r_hand':(39,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(29,33), 'r_hand':(39,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(29,33), 'r_hand':(39,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(29,33), 'r_hand':(39,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(29,33), 'r_hand':(39,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(29,33), 'r_hand':(39,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(29,33), 'r_hand':(39,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(29,33), 'r_hand':(39,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(29,34), 'r_hand':(39,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(29,34), 'r_hand':(39,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(37,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(29,34), 'r_hand':(39,33), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(29,34), 'r_hand':(39,34), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(29,34), 'r_hand':(39,34), 'l_hip':(30,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(30,34), 'r_hand':(39,34), 'l_hip':(29,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(30,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(37,26), 'l_hand':(30,34), 'r_hand':(39,34), 'l_hip':(29,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,34), 'r_hand':(38,34), 'l_hip':(29,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,34), 'r_hand':(38,34), 'l_hip':(29,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,34), 'r_hand':(38,34), 'l_hip':(29,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,34), 'r_hand':(38,34), 'l_hip':(29,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(34,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,34), 'r_hand':(38,34), 'l_hip':(29,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,34), 'r_hand':(38,34), 'l_hip':(29,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,34), 'r_hand':(38,34), 'l_hip':(29,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,34), 'r_hand':(38,34), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,34), 'r_hand':(38,34), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(38,34), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(38,34), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(28,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(38,34), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(28,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(38,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(28,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(37,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(28,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(37,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(28,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(37,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(29,44), 'r_knee':(35,44), 'l_foot':(28,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(37,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(29,44), 'r_knee':(35,44), 'l_foot':(28,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(37,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(29,44), 'r_knee':(35,44), 'l_foot':(28,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(37,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(29,44), 'r_knee':(35,44), 'l_foot':(28,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(37,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(29,44), 'r_knee':(35,44), 'l_foot':(28,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(37,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(28,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(37,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(28,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(38,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(28,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(38,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(28,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(38,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(28,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(27,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(38,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(38,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(38,33), 'l_hip':(29,32), 'r_hip':(34,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(38,33), 'l_hip':(29,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(38,33), 'l_hip':(29,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(38,33), 'l_hip':(29,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(35,56)},
    {'head':(32,11), 'neck':(32,14), 'l_shoulder':(28,17), 'r_shoulder':(36,17), 'l_elbow':(28,26), 'r_elbow':(36,26), 'l_hand':(30,33), 'r_hand':(38,33), 'l_hip':(29,32), 'r_hip':(35,32), 'l_knee':(30,44), 'r_knee':(35,44), 'l_foot':(29,56), 'r_foot':(34,56)},
]
# fmt: on

# Movement definitions: (name, frame_data, base_fps)
MOTION_LIST = [
    ('WALK',  WALK_FRAMES,  30.0),
    ('RUN',   RUN_FRAMES,   30.0),
    ('SNEAK', SNEAK_FRAMES, 30.0),
    ('MARCH', MARCH_FRAMES, 30.0),
    ('IDLE',  IDLE_FRAMES,  30.0),
]

# Joint names for iteration
JOINT_NAMES = list(WALK_FRAMES[0].keys())

# Bone connections: (from_joint, to_joint)
BONES = [
    ('head', 'neck'),
    # Shoulder bar + arms
    ('l_shoulder', 'r_shoulder'),
    ('neck', 'l_shoulder'),
    ('neck', 'r_shoulder'),
    ('l_shoulder', 'l_elbow'),
    ('l_elbow', 'l_hand'),
    ('r_shoulder', 'r_elbow'),
    ('r_elbow', 'r_hand'),
    # Spine + hip bar
    ('neck', 'l_hip'),
    ('neck', 'r_hip'),
    ('l_hip', 'r_hip'),
    # Legs
    ('l_hip', 'l_knee'),
    ('l_knee', 'l_foot'),
    ('r_hip', 'r_knee'),
    ('r_knee', 'r_foot'),
]

# Speed range (controlled by left/right)
SPEED_MIN = 0.25
SPEED_MAX = 3.0
SPEED_STEP = 0.25

# Colors
BODY_COLOR = (220, 200, 170)      # Warm white
JOINT_COLOR = (255, 240, 210)     # Brighter joints
HEAD_COLOR = (255, 245, 220)      # Brightest for head
HEAD_OUTLINE = (180, 165, 140)    # Slightly dimmer outline
SHADOW_COLOR = (30, 25, 20)       # Very dim shadow
GROUND_COLOR = (50, 45, 35)       # Subtle ground line
TRAIL_ALPHA = 0.25                # Ghost trail opacity

# Head shape: ~5px diameter circle (offsets from center)
HEAD_PIXELS = [
            (-1, -2), (0, -2), (1, -2),
    (-2, -1), (-1, -1), (0, -1), (1, -1), (2, -1),
    (-2,  0), (-1,  0), (0,  0), (1,  0), (2,  0),
    (-2,  1), (-1,  1), (0,  1), (1,  1), (2,  1),
            (-1,  2), (0,  2), (1,  2),
]
HEAD_OUTLINE_PIXELS = [
            (-1, -2), (0, -2), (1, -2),
    (-2, -1),                           (2, -1),
    (-2,  0),                           (2,  0),
    (-2,  1),                           (2,  1),
            (-1,  2), (0,  2), (1,  2),
]


def _lerp(a, b, t):
    return a + (b - a) * t


def _color_scale(color, scale):
    return (int(color[0] * scale), int(color[1] * scale), int(color[2] * scale))


class Walk(Visual):
    name = "MOVE"
    description = "Human motion"
    category = "digital"

    def reset(self):
        self.time = 0.0
        self._frame_float = 0.0
        self._motion_idx = 0  # Start with WALK
        self._speed = 1.0
        self._overlay_timer = 0.0

        self._init_positions()
        self._trail = {name: [] for name in ['l_hand', 'r_hand', 'l_foot', 'r_foot']}

    def _init_positions(self):
        """Reset drawn/float positions from current motion's first frame."""
        frames = MOTION_LIST[self._motion_idx][1]
        self._drawn_pos = {}
        self._float_pos = {}
        for name in JOINT_NAMES:
            pos = frames[0][name]
            self._drawn_pos[name] = pos
            self._float_pos[name] = (float(pos[0]), float(pos[1]))
        self._frame_float = 0.0

    def handle_input(self, input_state):
        consumed = False

        # Action: cycle movement
        if input_state.action_l or input_state.action_r:
            self._motion_idx = (self._motion_idx + 1) % len(MOTION_LIST)
            self._init_positions()
            self._trail = {name: [] for name in ['l_hand', 'r_hand', 'l_foot', 'r_foot']}
            self._overlay_timer = 2.0
            consumed = True

        # Left/Right: adjust speed
        if input_state.left_pressed:
            self._speed = max(SPEED_MIN, self._speed - SPEED_STEP)
            self._overlay_timer = 2.0
            consumed = True
        elif input_state.right_pressed:
            self._speed = min(SPEED_MAX, self._speed + SPEED_STEP)
            self._overlay_timer = 2.0
            consumed = True

        return consumed

    def update(self, dt):
        self.time += dt

        motion_name, frames, base_fps = MOTION_LIST[self._motion_idx]
        n = len(frames)

        # Advance frame
        self._frame_float += dt * base_fps * self._speed
        while self._frame_float >= n:
            self._frame_float -= n

        # Interpolate between adjacent frames
        fi = int(self._frame_float)
        frac = self._frame_float - fi
        frame_a = frames[fi % n]
        frame_b = frames[(fi + 1) % n]

        for name in JOINT_NAMES:
            ax, ay = frame_a[name]
            bx, by = frame_b[name]
            fx = _lerp(ax, bx, frac)
            fy = _lerp(ay, by, frac)
            self._float_pos[name] = (fx, fy)

            # Hysteresis: only update drawn pixel when float moves >0.55px
            dx_cur = self._drawn_pos[name][0]
            dy_cur = self._drawn_pos[name][1]
            dist_sq = (fx - dx_cur) ** 2 + (fy - dy_cur) ** 2
            if dist_sq > 0.55 * 0.55:
                self._drawn_pos[name] = (int(round(fx)), int(round(fy)))

        # Update trail
        for name in self._trail:
            pos = self._drawn_pos[name]
            trail = self._trail[name]
            if not trail or trail[-1] != pos:
                trail.append(pos)
            if len(trail) > 3:
                trail.pop(0)

        # Overlay fade
        if self._overlay_timer > 0:
            self._overlay_timer = max(0, self._overlay_timer - dt)

    def draw(self):
        d = self.display
        d.clear()

        # Ground line
        ground_y = 58
        for x in range(10, 54):
            d.set_pixel(x, ground_y, GROUND_COLOR)

        # Shadow (feet projected down to ground)
        for foot in ('l_foot', 'r_foot'):
            fx, fy = self._drawn_pos[foot]
            for dx in range(-1, 2):
                px = fx + dx
                if 0 <= px < 64:
                    alpha = 0.5 if dx == 0 else 0.3
                    c = _color_scale(SHADOW_COLOR, alpha / 0.5)
                    d.set_pixel(px, ground_y - 1, c)

        # Motion trail (faint ghosts on hands and feet)
        for name, trail in self._trail.items():
            for i, (tx, ty) in enumerate(trail[:-1]):
                age = len(trail) - 1 - i
                alpha = TRAIL_ALPHA / age
                c = _color_scale(BODY_COLOR, alpha)
                if 0 <= tx < 64 and 0 <= ty < 64:
                    d.set_pixel(tx, ty, c)

        # Draw bones (skip head-neck, head drawn separately)
        for j1, j2 in BONES:
            if j1 == 'head':
                continue
            x1, y1 = self._drawn_pos[j1]
            x2, y2 = self._drawn_pos[j2]
            is_torso = ((j1 == 'neck' and j2 in ('l_hip', 'r_hip'))
                        or (j1 == 'l_hip' and j2 == 'r_hip')
                        or (j1 == 'l_shoulder' and j2 == 'r_shoulder'))
            if is_torso:
                color = _color_scale(BODY_COLOR, 0.8)
            else:
                color = BODY_COLOR
            d.draw_line(x1, y1, x2, y2, color)

        # Draw joints as bright pixels (skip head)
        for name in JOINT_NAMES:
            if name == 'head':
                continue
            x, y = self._drawn_pos[name]
            if 0 <= x < 64 and 0 <= y < 64:
                d.set_pixel(x, y, JOINT_COLOR)

        # Head: filled circle ~5px diameter
        hx, hy = self._drawn_pos['head']
        for ox, oy in HEAD_PIXELS:
            px, py = hx + ox, hy + oy
            if 0 <= px < 64 and 0 <= py < 64:
                d.set_pixel(px, py, HEAD_COLOR)
        for ox, oy in HEAD_OUTLINE_PIXELS:
            px, py = hx + ox, hy + oy
            if 0 <= px < 64 and 0 <= py < 64:
                d.set_pixel(px, py, HEAD_OUTLINE)

        # Overlay
        if self._overlay_timer > 0:
            alpha = min(1.0, self._overlay_timer / 0.5)
            motion_name = MOTION_LIST[self._motion_idx][0]
            spd = f'{self._speed:.1f}x' if self._speed != int(self._speed) else f'{int(self._speed)}x'
            oc = (int(200 * alpha), int(200 * alpha), int(200 * alpha))
            d.draw_text_small(2, 2, f"{motion_name} {spd}", oc)
