#!/usr/bin/env python3
"""Write docs/GLOSSARY.md (internal; docs/ is gitignored) from tools/legend_ledger.json.

The ledger is the source for the Field Guide's "On screen" legends and for any
future printed manual; this report is the readable view of it.

The ledger is the audited record of on-screen text a viewer has to decode
(see tools/legend_audit.py). This renders it three ways: every label A-Z
(which shows where one label means different things in different items),
item by item, and the labels that are wrong rather than merely terse.

    python3 tools/build_glossary.py
"""
import json
import os
from collections import defaultdict

from legend_audit import LEDGER, ROOT, status_of

OUT = os.path.join(ROOT, "docs", "GLOSSARY.md")  # internal: docs/ is gitignored


def cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def explained(rec):
    if rec["explained_same_screen"]:
        return "on screen"
    bits = []
    if rec["on_site"]:
        bits.append("site only")
    if rec["spelled_out_elsewhere"]:
        bits.append("other screen")
    return ", ".join(bits) or "**nowhere**"


def main():
    with open(LEDGER) as f:
        ledger = json.load(f)
    entries = ledger["entries"]
    guide = json.load(open(os.path.join(ROOT, "site", "guide.json")))
    meta, order = {}, []
    for cat in guide["categories"]:
        for item in cat["items"]:
            key = f"{item['module']}::{item['cls']}"
            if key not in meta:
                meta[key] = (item["name"], cat["key"])
                order.append(key)

    # A visual hidden from the catalog (dev_only) still runs on a dev cabinet,
    # so the ledger, not the guide, decides what has been audited. Without this
    # its labels vanished from every table here and its name fell back to the
    # raw "module.py::Class" key — which is what hiding CELL did.
    for key in entries:
        if key not in meta:
            meta[key] = (f"{key.split('::')[-1].upper()} (hidden)", "hidden")
            order.append(key)

    audited = [k for k in order if k in entries]
    with_labels = [k for k in audited if entries[k]["labels"]]
    records = [(k, label, rec) for k in with_labels
               for label, rec in entries[k]["labels"].items()]
    nowhere = [r for r in records if explained(r[2]) == "**nowhere**"]

    out = ["# On-screen glossary", "",
           "What the abbreviations, codes and bare numbers on the panel mean — "
           "every piece of on-screen text a viewer has to decode, compiled from "
           "an audit of the catalog. Generated by `tools/build_glossary.py` from "
           "`tools/legend_ledger.json`; edit the ledger, not this file.", "",
           f"- {len(audited)} items audited, {len(with_labels)} have text that needs a legend",
           f"- {len(records)} labels; {len(nowhere)} are explained **nowhere** a viewer can see",
           "- \"on screen\" = spelled out on the panel at the same time as the label; "
           "\"other screen\" = the full word appears in another state of the same item "
           "(e.g. at game over); \"site only\" = the Field Guide explains it, the cabinet does not",
           ""]
    if ledger.get("_coverage"):
        out += ["**Coverage.** " + ledger["_coverage"], ""]

    # ── labels that say the wrong thing ──
    wrong = [r for r in records if r[2]["kind"] in ("mislabel", "truncation")]
    if wrong:
        out += ["## Wrong or cut off", "",
                "Labels that say the wrong thing or are cut short by the code. "
                "✓ = re-read in the code after the audit.", "",
                "| item | label | what it actually is | evidence | |", "|---|---|---|---|---|"]
        for k, label, rec in sorted(wrong, key=lambda r: r[2]["kind"]):
            out.append(f"| {cell(meta[k][0])} | `{cell(label)}` | {cell(rec['meaning'])} | "
                       f"{cell(rec['evidence'])} | {'✓' if rec.get('checked') else ''} |")
        out.append("")
    if ledger.get("_side_findings"):
        out += ["## Noticed along the way", "",
                "Not glossary entries — bugs, dead code and doc mismatches the audit "
                "turned up. Open items only; fixed ones move to the ledger's _fixed list."] + [""] +                [f"- {x}" for x in ledger["_side_findings"]] + [""]

    # ── labels the second pass found that have no full record yet ──
    if ledger.get("_unrecorded"):
        out += ["## Found in verification", "",
                "Labels the second pass saw drawn that the first audit missed. "
                "Not yet full records: no explained-where status, not counted above.", "",
                "| item | label | meaning | evidence |", "|---|---|---|---|"]
        for m in ledger["_unrecorded"]:
            name = meta.get(m["key"], (m["key"],))[0]
            out.append(f"| {cell(name)} | `{cell(m['label'])}` | {cell(m['meaning'])} | {cell(m['evidence'])} |")
        out.append("")

    # ── A-Z ──
    by_label = defaultdict(list)
    for k, label, rec in records:
        by_label[label].append((k, rec))
    out += ["## Every label, A–Z", "",
            "A label listed with more than one meaning is a collision: the same "
            "letters mean different things depending on what is running.", "",
            "| label | meaning | item | explained |", "|---|---|---|---|"]
    for label in sorted(by_label, key=lambda l: (l.lstrip("<{").upper(), l)):
        for k, rec in by_label[label]:
            out.append(f"| `{cell(label)}` | {cell(rec['meaning'])} | {cell(meta[k][0])} | {explained(rec)} |")
    out.append("")

    # ── item by item ──
    out += ["## Item by item", ""]
    cat = None
    for k in with_labels:
        name, c = meta[k]
        if c != cat:
            cat = c
            out += [f"### {cat}", ""]
        e = entries[k]
        out += [f"#### {name}", f"`{k}` · {status_of(e)}", "",
                "| label | as drawn | meaning | where | explained |", "|---|---|---|---|---|"]
        for label, rec in e["labels"].items():
            note = explained(rec)
            if rec["spelled_out_elsewhere"]:
                note += f" — {rec['spelled_out_elsewhere']}"
            out.append(f"| `{cell(label)}` | `{cell(rec['as_drawn'])}` | {cell(rec['meaning'])} | "
                       f"{cell(rec['where'])} | {cell(note)} |")
        out.append("")
        if e.get("other_encodings"):
            out += ["Also encoded without text:"] + [f"- {cell(x)}" for x in e["other_encodings"]] + [""]
        if e.get("notes"):
            out += [f"Audit note: {cell(e['notes'])}", ""]

    # ── non-text encodings in items whose text is fine ──
    rest = [k for k in audited if not entries[k]["labels"] and entries[k].get("other_encodings")]
    if rest:
        out += ["## Text is fine, but something else is encoded", ""]
        for k in rest:
            out += [f"**{meta[k][0]}** (`{k}`)"] + [f"- {cell(x)}" for x in entries[k]["other_encodings"]] + [""]

    clear = [meta[k][0] for k in audited if not entries[k]["labels"] and not entries[k].get("other_encodings")]
    if clear:
        out += ["## Audited, nothing to decode", "", ", ".join(clear), ""]

    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print(f"{OUT}: {len(records)} labels across {len(with_labels)} items ({len(nowhere)} explained nowhere)")


if __name__ == "__main__":
    main()
