#!/usr/bin/env python3
"""Write SOURCES.md from tools/sources_ledger.json.

The ledger is the audited record of where the catalog's factual claims come
from — the attribution lines the cabinet shows, and the tables typed or
generated from somewhere outside this repo. This renders it four ways: the
lines that should change, the claims nobody could settle, the items whose code
does not implement what they credit, and then every claim item by item.

    python3 tools/build_sources.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEDGER = os.path.join(ROOT, "tools", "sources_ledger.json")
OUT = os.path.join(ROOT, "SOURCES.md")


def cell(text):
    return str(text or "").replace("|", "\\|").replace("\n", " ").strip()


def first_sentence(text, limit=240):
    s = cell(text)
    for end in (". ", "; "):
        if end in s[:limit]:
            return s[:s.index(end) + 1]
    return s[:limit] + ("…" if len(s) > limit else "")


def link(claim):
    """A citation is only a citation if a reader can reach it."""
    src, url = cell(claim.get("source")), cell(claim.get("url"))
    if not src:
        return "—"
    return f"[{src}]({url})" if url else src


def main():
    with open(LEDGER) as f:
        ledger = json.load(f)
    entries = ledger["entries"]

    guide = json.load(open(os.path.join(ROOT, "site", "guide.json")))
    order = [c["key"] for c in guide["categories"]]
    by_cat = {}
    for key, e in entries.items():
        by_cat.setdefault(e["category"], []).append((key, e))

    records = [(k, e, c) for k, e in entries.items() for c in e["claims"]]
    counts = {}
    for _, _, c in records:
        counts[c.get("verdict") or "unreviewed"] = counts.get(c.get("verdict") or "unreviewed", 0) + 1
    checked = [r for r in records if r[2].get("checked")]
    corrections = [r for r in records
                   if r[2].get("verdict") not in (None, "correct") and r[2].get("proposed_claim")]
    unsettled = [r for r in records if r[2].get("verdict") == "unverifiable"]
    mismatched = [r for r in records if r[2].get("code_matches") in ("no", "partly")]

    out = ["# Sources", "",
           "Where the catalog's factual claims come from. Generated by "
           "`tools/build_sources.py` from `tools/sources_ledger.json`; edit the "
           "ledger, not this file.", "",
           f"- {len(entries)} items, {len(records)} claims",
           "- " + ", ".join(f"**{n} {v}**" for v, n in sorted(counts.items(), key=lambda kv: -kv[1])),
           f"- {len(checked)} read against a fetched source and dated; "
           f"{len(records) - len(checked)} not",
           f"- {len(corrections)} lines have a correction proposed; "
           f"{len(mismatched)} items implement something other than what they credit",
           "",
           "\"Credit\" is the attribution line the cabinet and the Field Guide "
           "show. \"Data\" is a table typed or generated from somewhere else. "
           "\"Experiment\" is a result of our own.", ""]
    if ledger.get("_audit"):
        out += ["**How this was checked.** " + ledger["_audit"], ""]
    if ledger.get("_coverage"):
        out += ["**Coverage.** " + ledger["_coverage"], ""]

    if corrections:
        out += ["## Lines that should change", "",
                "The claim on the left is what the cabinet and the Field Guide "
                "show today. Nothing here has been applied to the code.", "",
                "| Item | Shows now | Should read | Why | Asserted at |",
                "|---|---|---|---|---|"]
        for _, e, c in sorted(corrections, key=lambda r: r[1]["name"]):
            out.append(f"| {cell(e['name'])} | {cell(c['claim'])} "
                       f"| **{cell(c['proposed_claim'])}** | {first_sentence(c.get('ruling'))} "
                       f"| `{cell(c['evidence'])}` |")
        out.append("")

    if unsettled:
        out += ["## Not settled", "",
                "No primary source was found this session. These are recorded "
                "unverified rather than given a citation that reads well.", "",
                "| Item | Claim | What was tried | Asserted at |", "|---|---|---|---|"]
        for _, e, c in sorted(unsettled, key=lambda r: r[1]["name"]):
            out.append(f"| {cell(e['name'])} | {cell(c['claim'])} "
                       f"| {first_sentence(c.get('ruling'), 320)} | `{cell(c['evidence'])}` |")
        out.append("")

    if mismatched:
        out += ["## The code and the credit disagree", "",
                "What the panel draws is not (or not only) the thing named on it.", "",
                "| Item | Credits | Implements | Asserted at |", "|---|---|---|---|"]
        for _, e, c in sorted(mismatched, key=lambda r: r[1]["name"]):
            out.append(f"| {cell(e['name'])} | {cell(c['claim'])} ({c['code_matches']}) "
                       f"| {first_sentence(c.get('code_note'), 320)} | `{cell(c['evidence'])}` |")
        out.append("")

    out += ["## Every claim, item by item", ""]
    for cat in [c for c in order if c in by_cat] + [c for c in by_cat if c not in order]:
        out += [f"### {cat}", "",
                "| Item | Kind | Claim | Verdict | Source | Checked |",
                "|---|---|---|---|---|---|"]
        for _, e in sorted(by_cat[cat], key=lambda kv: kv[1]["name"]):
            for c in e["claims"]:
                out.append(
                    f"| {cell(e['name'])} | {c['kind']} | {cell(c['claim'])} "
                    f"| {c.get('verdict') or 'unreviewed'} | {link(c)} "
                    f"| {c.get('checked') or '—'} |")
        out.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {os.path.relpath(OUT, ROOT)}: {len(entries)} items, {len(records)} claims, "
          f"{len(checked)} dated, {len(corrections)} corrections, {len(unsettled)} unsettled, "
          f"{len(mismatched)} code/credit mismatches")


if __name__ == "__main__":
    main()
