#!/usr/bin/env python3
"""Write the rows of site/history.html from tools/history.json.

history.json is the public timeline ("A History of Ideas"): one row per idea,
with the date shown, the category label, and the catalog item it refers to.
Only the table body between the two GENERATED markers is rewritten; the rest
of the page is hand-edited like the other site pages.

The build refuses to write when a row is out of step with what the cabinet
ships: an item that is no longer in site/catalog.json, a painting not in
tools/paintings.json, or a date that contradicts the audited credit line in
tools/sources_ledger.json (the date must appear in the claim, e.g. "1450s" in
"Johannes Gutenberg, Mainz, 1450s"). A row may carry "date_source" to explain
a date that is not in the claim.

    python3 tools/build_history.py
"""
import html
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROWS = os.path.join(ROOT, "tools", "history.json")
LEDGER = os.path.join(ROOT, "tools", "sources_ledger.json")
CATALOG = os.path.join(ROOT, "site", "catalog.json")
PAINTINGS = os.path.join(ROOT, "tools", "paintings.json")
OUT = os.path.join(ROOT, "site", "history.html")

BEGIN = "      <!-- GENERATED by tools/build_history.py from tools/history.json: edit that, not this -->\n"
END = "      <!-- /GENERATED -->\n"

ERAS = [  # first year of each era, in order
    (-10000, "ANCIENT WORLD"),
    (1000, "MEDIEVAL &amp; RENAISSANCE"),
    (1750, "AGE OF INDUSTRY"),
    (1880, "TURN OF CENTURY"),
    (1930, "MID-CENTURY"),
    (1970, "THE COMPUTER AGE"),
    (1980, "GOLDEN AGE OF ARCADES"),
    (1983, "8-BIT &amp; BEYOND"),
    (1997, "CONNECTED ERA"),
]


def year_of(row):
    """Sort key from the shown date: '~3200 BC' -> -3200, '1450s' -> 1450."""
    if "year" in row:
        return row["year"]
    d = row["date"].lstrip("~")
    bc = d.endswith(" BC")
    n = int(d.removesuffix(" BC").rstrip("s"))
    return -n if bc else n


def date_in_claim(date, claim):
    d = date.lstrip("~")
    return d in claim or f"'{d[-2:]}" in claim  # "Lorenz '63"


def main():
    rows = json.load(open(ROWS))
    ledger = json.load(open(LEDGER))["entries"]
    paintings = json.load(open(PAINTINGS))
    catalog = {f"{i['module']}::{i['cls']}"
               for c in json.load(open(CATALOG))["categories"] for i in c["items"]}

    errors = []
    for r in rows:
        if r.get("painting"):
            if r["painting"] not in paintings:
                errors.append(f"{r['name']}: painting {r['painting']!r} not in paintings.json")
                continue
            r["year"] = paintings[r["painting"]]["year"]
            r["date"] = str(r["year"])
            continue
        if r.get("item") is None:
            if not r.get("note"):
                errors.append(f"{r['name']}: no item and no note saying why")
            continue
        if r["item"] not in catalog:
            errors.append(f"{r['name']}: {r['item']} is not in site/catalog.json")
        credits = [c["claim"] for c in ledger.get(r["item"], {}).get("claims", [])
                   if c["kind"] == "credit"]
        if credits and not r.get("date_source") \
                and not any(date_in_claim(r["date"], c) for c in credits):
            errors.append(f"{r['name']}: date {r['date']!r} is not in the ledger credit "
                          f"{' / '.join(credits)!r} (add date_source if that is deliberate)")
    if errors:
        print("history.json disagrees with what ships:\n  " + "\n  ".join(errors), file=sys.stderr)
        sys.exit(1)

    # Dated ledger credits no row refers to: not an error, but worth seeing.
    # A LAB is the same idea as its parent item and never gets a row of its own.
    claimed = {c["claim"] for r in rows if r.get("item") in ledger
               for c in ledger[r["item"]]["claims"] if c["kind"] == "credit"}
    missing = [f"{e['name']} ({c['claim']})" for e in ledger.values() for c in e["claims"]
               if c["kind"] == "credit" and c["claim"] not in claimed
               and not e["name"].endswith(" LAB")
               and (re.search(r"\d{4}", c["claim"]) or "BC" in c["claim"])]

    rows.sort(key=lambda r: (year_of(r), r["date"].startswith("~"), r["name"]))
    body = []
    era = None
    for r in rows:
        y = year_of(r)
        label = [lab for start, lab in ERAS if y >= start][-1]
        if label != era:
            body.append(f'      <tr class="era"><td colspan="3">{label}</td></tr>\n')
            era = label
        body.append(f'      <tr><td class="n num">{html.escape(r["date"], quote=False)}</td>'
                    f'<td class="nm">{html.escape(r["name"], quote=False)}</td>'
                    f'<td class="cat">{html.escape(r["cat"], quote=False)}</td></tr>\n')

    page = open(OUT).read()
    start, end = page.index(BEGIN) + len(BEGIN), page.index(END)
    with open(OUT, "w") as f:
        f.write(page[:start] + "".join(body) + page[end:])

    ledgered = sum(1 for r in rows if r.get("item") in ledger)
    print(f"wrote {os.path.relpath(OUT, ROOT)}: {len(rows)} rows, {ledgered} checked against "
          f"the ledger, {sum(1 for r in rows if r.get('painting'))} dated from paintings.json, "
          f"{len(rows) - ledgered - sum(1 for r in rows if r.get('painting'))} unverified")
    if missing:
        print("dated ledger credits with no timeline row:\n  " + "\n  ".join(missing))


if __name__ == "__main__":
    main()
