#!/usr/bin/env python3
"""
Build the MUSIC BOX visual's pin data from a real score.

Reads assets/musicbox/entertainer.mid and writes visuals/musicbox_data.py.
The MIDI file is the Mutopia Project's typesetting of Scott Joplin's "The
Entertainer" (Mutopia-2016/11/25-263, from a reproduction of the 1902 original
edition, released into the public domain by its typesetter); it lives at
https://www.mutopiaproject.org/ftp/JoplinS/entertainer/ and in the hatch
library's mirror of that tree.

A music box comb is cut for its tune, so the comb here gets one tooth for
every pitch the piece uses and nothing is transposed or left out. What the
conversion keeps and loses:
  - every note's pitch and start, rounded to 1/24 of a quarter note
  - note lengths are dropped: a comb tooth is plucked and rings, it cannot hold
  - both hands land on the one comb; a pitch both play at once is one pin
  - repeats are played out, as this MIDI file plays them

Usage (needs mido, which the dev venv has):
    ../.venv313/bin/python tools/build_music_box.py
"""

import os

from build_piano_rolls import ROOT, TICKS_PER_BEAT, read_notes

MIDI = os.path.join(ROOT, 'assets', 'musicbox', 'entertainer.mid')
OUT = os.path.join(ROOT, 'visuals', 'musicbox_data.py')

TITLE = 'THE ENTERTAINER'
COMPOSER = 'JOPLIN'


def main():
    bpm, notes = read_notes(MIDI)
    comb = sorted({pitch for _, _, pitch, _ in notes})
    pins = sorted({(start, comb.index(pitch)) for start, _, pitch, _ in notes})
    print(f'{TITLE}: {len(notes)} notes -> {len(pins)} pins on a {len(comb)}-tooth comb, '
          f'{bpm} bpm, {pins[-1][0] / TICKS_PER_BEAT / bpm * 60:.0f}s')
    lines = [
        '"""Pin data for the MUSIC BOX visual.',
        '',
        'GENERATED by tools/build_music_box.py from the Mutopia Project MIDI file',
        'in assets/musicbox/ - edit the tool, not this file.',
        '',
        'COMB is the pitch of each tooth (MIDI note numbers, bass first). Each pin',
        'is (start, tooth): start in ticks of 1/TICKS_PER_BEAT of a quarter note,',
        'tooth an index into COMB.',
        '"""',
        '',
        f'TITLE = {TITLE!r}',
        f'COMPOSER = {COMPOSER!r}',
        f'BPM = {bpm}',
        f'TICKS_PER_BEAT = {TICKS_PER_BEAT}',
        '',
        f'COMB = {comb!r}',
        '',
        'PINS = [',
    ]
    for i in range(0, len(pins), 10):
        lines.append('    ' + ''.join(f'({s},{t}),' for s, t in pins[i:i + 10]))
    lines.append(']')
    with open(OUT, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'Wrote {OUT}')


if __name__ == '__main__':
    main()
