#!/usr/bin/env python3
"""Write visuals/credits_data.py: the attribution block of the CREDITS roll from
tools/sources_ledger.json, and the counts the roll quotes from site/guide.json.

One section per catalog category (in Field Guide order); within it, items that
share a credit line are listed together above that line. Only "credit" claims
appear, and none the audit ruled not_an_attribution: with no outside source to
name, an honest roll says nothing. Everything is uppercased, stripped of
accents and punctuation the 3x5 font lacks, and wrapped to the 15 characters
that fit across the 64-pixel panel.

    python3 tools/build_credits.py
"""
import json
import os
import re
import unicodedata

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEDGER = os.path.join(ROOT, "tools", "sources_ledger.json")
GUIDE = os.path.join(ROOT, "site", "guide.json")
OUT = os.path.join(ROOT, "visuals", "credits_data.py")

WIDTH = 15  # chars: x=2, 4px advance, 3px glyph -> 15 fit in 64px
FONT = set("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 :-.!?+#/&()~")


def roll_text(s):
    """What the 3x5 font can show: uppercase ASCII, no commas or apostrophes."""
    s = unicodedata.normalize("NFKD", s)
    s = "".join(ch for ch in s if not unicodedata.combining(ch))
    s = re.sub(r"\bc\. (?=\d)", "~", s.replace("–", "-").replace("—", "-"))
    s = s.replace(",", "").replace("'", "").replace("’", "").upper()
    bad = set(s) - FONT
    assert not bad, f"{s!r}: the 3x5 font has no {sorted(bad)}"
    return s


def wrap(text):
    """Greedy word wrap; a word wider than the panel breaks after a hyphen."""
    words = []
    for w in text.split():
        while len(w) > WIDTH and "-" in w[:WIDTH]:
            cut = w.rfind("-", 0, WIDTH) + 1
            words.append(w[:cut])
            w = w[cut:]
        assert len(w) <= WIDTH, f"{w!r} does not fit in {WIDTH} characters"
        words.append(w)
    lines, cur = [], ""
    for w in words:
        if cur and len(cur) + 1 + len(w) > WIDTH:
            lines.append(cur)
            cur = w
        else:
            cur = f"{cur} {w}" if cur else w
    return lines + [cur] if cur else lines


def pack(names):
    """Names side by side, two spaces apart, never splitting one across lines."""
    lines, cur = [], ""
    for n in names:
        if len(n) > WIDTH:
            if cur:
                lines.append(cur)
                cur = ""
            lines += wrap(n)
        elif cur and len(cur) + 2 + len(n) > WIDTH:
            lines.append(cur)
            cur = n
        else:
            cur = f"{cur}  {n}" if cur else n
    return lines + [cur] if cur else lines


def main():
    entries = json.load(open(LEDGER))["entries"]
    guide = json.load(open(GUIDE))
    cats = [(c["key"], c["name"]) for c in guide["categories"]]
    counts = dict(guide["meta"], **{c["key"]: len(c["items"]) for c in guide["categories"]})

    lines = []
    for key, cat_name in cats:
        groups = {}  # claim -> names, in name order
        for e in sorted(entries.values(), key=lambda e: e["name"]):
            if e["category"] != key:
                continue
            for c in e["claims"]:
                if c["kind"] == "credit" and c.get("verdict") != "not_an_attribution":
                    groups.setdefault(c["claim"], []).append(roll_text(e["name"]))
        if not groups:
            continue
        header = f"- {cat_name} -"
        lines += [(header if len(header) <= WIDTH else cat_name, "M"), ("", "G")]
        for claim, names in groups.items():
            lines += [(t, "C") for t in pack(names)]
            for phrase in claim.replace(" · ", "; ").split("; "):
                lines += [(t, "W") for t in wrap(roll_text(phrase))]
            lines.append(("", "G"))

    assert all(len(t) <= WIDTH for t, _ in lines)
    with open(OUT, "w") as f:
        f.write("# GENERATED by tools/build_credits.py from tools/sources_ledger.json.\n"
                "# Edit the ledger, then rerun the tool. Colours: C cyan, W white, G gray, M magenta.\n"
                "ATTRIBUTIONS = [\n")
        f.writelines(f"    ({t!r}, {c!r}),\n" for t, c in lines)
        f.write("]\n\n# How many of each thing ships: guide.json meta plus items per category.\n"
                f"COUNTS = {json.dumps(counts, sort_keys=True)}\n")
    print(f"wrote {os.path.relpath(OUT, ROOT)}: {len(lines)} lines, "
          f"{sum(1 for _, c in lines if c == 'M')} sections")


if __name__ == "__main__":
    main()
