#!/usr/bin/env python3
"""
Build the PIANO ROLL visual's note data from real scores.

Reads the MIDI files in assets/pianoroll/ and writes visuals/pianoroll_data.py.
The MIDI files come from the Mutopia Project (mutopiaproject.org): each is the
MIDI that LilyPond produced from a volunteer's typesetting of a public-domain
score, and each of these eight was released by its typesetter into the public
domain. The 'mutopia' path below is the piece's directory under
https://www.mutopiaproject.org/ftp/ - the same tree the hatch library mirrors.

What the conversion keeps and loses:
  - every note's pitch, start and length, rounded to 1/24 of a quarter note
  - which staff it was written on (upper = right hand, lower = left hand)
  - one tempo per piece (each of these files has exactly one)
  - written repeats are played once, as LilyPond's MIDI plays them
  - the roll shows 64 keys; a piece wider than that has its few outlying
    notes moved an octave inward, and the count is reported and recorded

Usage (needs mido, which the dev venv has):
    ../.venv313/bin/python tools/build_piano_rolls.py
"""

import os

import mido

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MIDI_DIR = os.path.join(ROOT, 'assets', 'pianoroll')
OUT = os.path.join(ROOT, 'visuals', 'pianoroll_data.py')

TICKS_PER_BEAT = 24
NUM_KEYS = 64
PIANO_LOW, PIANO_HIGH = 21, 108   # A0..C8, the 88 keys

# (file, title on the panel, composer on the panel, mutopia path)
ROLLS = [
    ('gymnopedie_1.mid', 'GYMNOPEDIE NO 1', 'SATIE',
     'SatieE/gymnopedie_1'),
    ('wtk1-prelude1.mid', 'PRELUDE IN C', 'BACH',
     'BachJS/BWV846/wtk1-prelude1'),
    ('bach-invention-08.mid', 'INVENTION NO 8', 'BACH',
     'BachJS/BWV779/bach-invention-08'),
    ('fur_Elise_WoO59.mid', 'FUR ELISE', 'BEETHOVEN',
     'BeethovenLv/WoO59/fur_Elise_WoO59'),
    ('Chop-28-20.mid', 'PRELUDE NO 20', 'CHOPIN',
     'ChopinFF/O28/Chop-28-20'),
    ('chopin_valse_op64_no1.mid', 'MINUTE WALTZ', 'CHOPIN',
     'ChopinFF/O64/chopin_valse_op64_no1'),
    ('TheStarsAndStripesForever.mid', 'STARS & STRIPES', 'SOUSA',
     'SousaJP/TheStarsAndStripesForever'),
    ('maple.mid', 'MAPLE LEAF RAG', 'JOPLIN',
     'JoplinS/maple'),
]


def read_notes(path):
    """Return (bpm, [(start, dur, pitch, hand)]) with times in MIDI ticks."""
    mid = mido.MidiFile(path)
    tempos = set()
    staves = []   # one note list per track that has notes
    for track in mid.tracks:
        notes, sounding, t = [], {}, 0
        for msg in track:
            t += msg.time
            if msg.type == 'set_tempo':
                tempos.add(msg.tempo)
            elif msg.type == 'note_on' and msg.velocity > 0:
                sounding.setdefault(msg.note, []).append(t)
            elif msg.type in ('note_off', 'note_on') and sounding.get(msg.note):
                start = sounding[msg.note].pop(0)
                notes.append((start, t - start, msg.note))
        if notes:
            staves.append(notes)
    if len(tempos) != 1:
        raise SystemExit(f'{path}: expected one tempo, found {len(tempos)}')
    if len(staves) != 2:
        raise SystemExit(f'{path}: expected two staves, found {len(staves)}')
    # The files don't agree on which staff comes first, so go by pitch:
    # the higher-lying staff is the right hand.
    staves.sort(key=lambda s: -sum(n[2] for n in s) / len(s))
    scale = TICKS_PER_BEAT / mid.ticks_per_beat
    out = []
    for hand, notes in enumerate(staves):
        for start, dur, pitch in notes:
            out.append((round(start * scale), max(1, round(dur * scale)), pitch, hand))
    out.sort()
    return round(mido.tempo2bpm(tempos.pop())), out


def fit_window(notes):
    """Pick the 64-key window; return (low, notes, how many were moved)."""
    pitches = [n[2] for n in notes]
    lo, hi = min(pitches), max(pitches)
    if hi - lo < NUM_KEYS:
        low = lo - (NUM_KEYS - (hi - lo + 1)) // 2      # centre the piece
    else:
        low = max(range(lo, hi - NUM_KEYS + 2),
                  key=lambda w: sum(w <= p < w + NUM_KEYS for p in pitches))
    low = max(PIANO_LOW, min(PIANO_HIGH - NUM_KEYS + 1, low))
    moved, fitted = 0, []
    for start, dur, pitch, hand in notes:
        if not low <= pitch < low + NUM_KEYS:
            moved += 1
            while pitch < low:
                pitch += 12
            while pitch >= low + NUM_KEYS:
                pitch -= 12
        fitted.append((start, dur, pitch, hand))
    return low, fitted, moved


def main():
    lines = [
        '"""Note data for the PIANO ROLL visual.',
        '',
        'GENERATED by tools/build_piano_rolls.py from the Mutopia Project MIDI',
        'files in assets/pianoroll/ - edit the tool, not this file.',
        '',
        "Each note is (start, length, pitch, hand): start and length in ticks of",
        "1/TICKS_PER_BEAT of a quarter note, pitch as a MIDI note number, hand 0",
        "for the upper staff (right hand) and 1 for the lower (left hand).",
        "'low' is the pitch of the roll's leftmost key.",
        '"""',
        '',
        f'TICKS_PER_BEAT = {TICKS_PER_BEAT}',
        '',
        'ROLLS = [',
    ]
    for fname, title, composer, mutopia in ROLLS:
        bpm, notes = read_notes(os.path.join(MIDI_DIR, fname))
        low, notes, moved = fit_window(notes)
        end = max(n[0] + n[1] for n in notes)
        print(f'{title:16} {composer:10} {len(notes):5} notes  {bpm:3} bpm  '
              f'{end / TICKS_PER_BEAT / bpm * 60:5.0f}s  keys {low}-{low + NUM_KEYS - 1}'
              f'  moved {moved}')
        lines.append(f'    # {mutopia}  ({moved} notes moved an octave to fit)')
        lines.append(f"    {{'title': {title!r}, 'composer': {composer!r}, "
                     f"'bpm': {bpm}, 'low': {low}, 'notes': [")
        for i in range(0, len(notes), 6):
            lines.append('        ' + ''.join(
                f'({s},{d},{p},{h}),' for s, d, p, h in notes[i:i + 6]))
        lines.append('    ]},')
    lines.append(']')
    with open(OUT, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'Wrote {OUT}')


if __name__ == '__main__':
    main()
